const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
const nf=n=>new Intl.NumberFormat('fr-FR').format(Number(n||0));
const f2=n=>Number(n||0)>0?Number(n).toFixed(2):'—';
const date=ts=>ts?new Date(Number(ts)*1000).toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit'}):'—';
const datetime=ts=>ts?new Date(Number(ts)*1000).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const state={c:1,p:1};let timer;
async function get(url,opt){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erreur serveur');return d}
function tab(id){$$('.nav button').forEach(b=>b.classList.toggle('on',b.dataset.tab===id));$$('.tab').forEach(x=>x.classList.toggle('on',x.id===id));if(id==='clubs')loadClubs();if(id==='players')loadPlayers();if(id==='matches')loadMatches();if(id==='rank')loadRank()}
$$('.nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function rawRating(p){if(+p.rating>0)return +p.rating;try{const r=JSON.parse(p.raw_json||'{}'),v=Number(r.ratingAve??r.rating??r.averageRating??r.avgRating??0);return v>10&&v<=100?v/10:v}catch{return 0}}
function pos(p){return p.position||p.recent_role||'—'}
async function dash(){try{const[d,s]=await Promise.all([get('/api/dashboard'),get('/api/crawl')]);$('#heroClubs').textContent=nf(d.clubs);$('#stats').innerHTML=`<div class="stat"><b>${nf(d.clubs)}</b><small>Clubs indexés</small></div><div class="stat"><b>${nf(d.players)}</b><small>Joueurs</small></div><div class="stat"><b>${nf(d.matches)}</b><small>Matchs archivés</small></div><div class="stat"><b>${nf(d.appearances)}</b><small>Performances joueurs</small></div><div class="stat"><b>${d.persistent?'ON':'OFF'}</b><small>Base persistante</small></div>`;$('#status').innerHTML=`<span class="dot"></span><b>${d.persistent?'PostgreSQL persistante':'Stockage temporaire'}</b> <span class="muted">• Indexation ${s.running?'en cours':'en attente'} • ${nf(s.scanned)} recherches • ${nf(s.discovered)} clubs détectés • ${nf(s.clubsSynced)} clubs enrichis • ${nf(s.playersRead)} joueurs lus • ${nf(s.matchesRead)} matchs lus${s.prefix?' • préfixe '+esc(s.prefix):''}${s.lastError?' • dernière réponse '+esc(s.lastError):''}</span>`}catch(e){console.error(e)}}
function clubCard(c){const t=+c.wins + +c.draws + +c.losses,w=t?Math.round(+c.wins/t*100):0;return `<article class="card click" data-club="${esc(c.platform)}|${esc(c.club_id)}"><div class="top"><div><div class="name">${esc(c.name)}</div><div class="muted">${esc(c.platform_label||c.platform)} • ID ${esc(c.club_id)}</div></div><span class="pill">${esc(c.platform_label||'FC26')}</span></div><div class="metrics"><div class="metric"><b>${nf(c.skill)}</b><span>Skill</span></div><div class="metric"><b>${nf(c.games)}</b><span>Matchs</span></div><div class="metric"><b>${w}%</b><span>Victoires</span></div></div></article>`}
function playerCard(p){const r=rawRating(p);return `<article class="card click" data-player="${esc(p.platform)}|${esc(p.player_id)}"><div class="top"><div><div class="name">${esc(p.name)}</div><div class="muted">${esc(p.club_name||'Club inconnu')}</div></div><span class="tag">${esc(pos(p))}</span></div><div class="metrics"><div class="metric"><b class="rating">${f2(r)}</b><span>Note</span></div><div class="metric"><b>${nf(p.goals)}</b><span>Buts</span></div><div class="metric"><b>${nf(p.assists)}</b><span>Passes</span></div></div><div class="muted">${nf(p.games)} matchs${p.archetype_name?' • '+esc(p.archetype_name):''}${p.signature_playstyle?' • '+esc(p.signature_playstyle):''}</div></article>`}
function bindCards(root=document){root.querySelectorAll('[data-club]').forEach(x=>x.onclick=()=>{const[p,id]=x.dataset.club.split('|');openClub(p,id)});root.querySelectorAll('[data-player]').forEach(x=>x.onclick=()=>{const[p,id]=x.dataset.player.split('|');openPlayer(p,id)})}
function matchHtml(m,clubId=''){let result='';if(clubId){const home=String(m.home_club_id)===String(clubId),gf=home?+m.home_goals:+m.away_goals,ga=home?+m.away_goals:+m.home_goals;result=gf>ga?'V':gf<ga?'D':'N'}return `<div class="match"><div class="home">${esc(m.home_name||'—')}</div><div class="scoreBox">${nf(m.home_goals)} - ${nf(m.away_goals)}</div><div class="away">${esc(m.away_name||'—')}<div class="muted">${datetime(m.ts)} • ${esc((m.match_type||'').replace('Match',''))}</div></div>${result?`<span class="result ${result}">${result}</span>`:'<span></span>'}</div>`}
async function overview(){try{const o=await get('/api/overview');$('#recentClubs').innerHTML=o.recentClubs.map(c=>`<div class="line click" data-club="${esc(c.platform)}|${esc(c.club_id)}"><div><b>${esc(c.name)}</b><div class="muted">${esc(c.platform_label)}</div></div><span>${nf(c.skill)} skill</span></div>`).join('')||'<div class="muted">Indexation en cours…</div>';$('#topPlayers').innerHTML=o.topPlayers.map(p=>`<div class="line click" data-player="${esc(p.platform)}|${esc(p.player_id)}"><div><b>${esc(p.name)}</b><div class="muted">${esc(p.club_name||'—')} ${p.position?'• '+esc(p.position):''}</div></div><span>${nf(p.goals)} ⚽ • ${f2(rawRating(p))}</span></div>`).join('')||'<div class="muted">Indexation en cours…</div>';$('#homeMatches').innerHTML=o.matches.map(matchHtml).join('')||'<div class="muted">Les matchs archivés vont apparaître ici.</div>';bindCards($('#home'))}catch(e){console.error(e)}}
async function search(){const q=$('#q').value.trim(),platform=$('#platform').value;if(!q){$('#searchResults').classList.add('hide');return}try{const a=await get('/api/search?q='+encodeURIComponent(q)+'&platform='+encodeURIComponent(platform));$('#hclubs').innerHTML=a.clubs.map(c=>`<div class="line click" data-club="${esc(c.platform)}|${esc(c.club_id)}"><div><b>${esc(c.name)}</b><div class="muted">${esc(c.platform_label)}</div></div><span>${nf(c.skill)} skill</span></div>`).join('')||'<div class="muted">Aucun club dans la base.</div>';$('#hplayers').innerHTML=a.players.map(p=>`<div class="line click" data-player="${esc(p.platform)}|${esc(p.player_id)}"><div><b>${esc(p.name)}</b><div class="muted">${esc(p.club_name||'—')} • ${esc(pos(p))}</div></div><span>${f2(rawRating(p))}</span></div>`).join('')||'<div class="muted">Aucun joueur dans la base.</div>';$('#searchResults').classList.remove('hide');tab('home');bindCards($('#searchResults'));$('#searchResults').scrollIntoView({behavior:'smooth',block:'start'})}catch(e){alert(e.message)}}
$('#searchForm').addEventListener('submit',e=>{e.preventDefault();search()});
$('#eaSearch').onclick=async()=>{const q=$('#q').value.trim();if(q.length<2)return alert('Écris au moins 2 caractères.');const b=$('#eaSearch'),old=b.textContent;b.disabled=true;b.innerHTML='<span class="loader"></span> Recherche EA…';try{const r=await get('/api/discover?q='+encodeURIComponent(q)+'&platform='+encodeURIComponent($('#platform').value),{method:'POST'});b.textContent=`${r.found} club(s) trouvé(s)`;await search();await dash();setTimeout(()=>b.textContent=old,2500)}catch(e){alert(e.message);b.textContent=old}finally{b.disabled=false}};
function pager(el,p,pages,fn){el.innerHTML=`<button ${p<=1?'disabled':''}>←</button><span>Page ${p}/${pages}</span><button ${p>=pages?'disabled':''}>→</button>`;const b=el.querySelectorAll('button');b[0].onclick=()=>p>1&&fn(p-1);b[1].onclick=()=>p<pages&&fn(p+1)}
async function loadClubs(){const r=await get('/api/clubs?q='+encodeURIComponent($('#cq').value)+'&platform='+encodeURIComponent($('#cp').value)+'&sort='+$('#cs').value+'&page='+state.c);$('#ccount').textContent=nf(r.total)+' clubs';$('#cgrid').innerHTML=r.items.map(clubCard).join('')||'<div class="muted">Aucun club.</div>';pager($('#cpager'),r.page,r.pages,x=>{state.c=x;loadClubs()});bindCards($('#cgrid'))}
async function loadPlayers(){const r=await get('/api/players?q='+encodeURIComponent($('#pq').value)+'&platform='+encodeURIComponent($('#pp').value)+'&sort='+$('#ps').value+'&page='+state.p);$('#pcount').textContent=nf(r.total)+' joueurs';$('#pgrid').innerHTML=r.items.map(playerCard).join('')||'<div class="muted">Aucun joueur.</div>';pager($('#ppager'),r.page,r.pages,x=>{state.p=x;loadPlayers()});bindCards($('#pgrid'))}
async function loadMatches(){const r=await get('/api/matches?platform='+encodeURIComponent($('#mp').value));$('#matchGrid').innerHTML=r.items.map(matchHtml).join('')||'<div class="muted">Aucun match archivé pour le moment.</div>'}
async function loadRank(){const r=await get('/api/rankings?platform='+encodeURIComponent($('#rp').value)+'&metric='+$('#rm').value);$('#rrows').innerHTML=r.items.map((x,i)=>`<div class="tr click" data-player="${esc(x.platform)}|${esc(x.player_id)}"><b>#${i+1}</b><div><b>${esc(x.name)}</b><div class="muted">${esc(x.platform_label)}</div></div><div>${esc(x.club_name||'—')}</div><div>${esc(pos(x))}</div><div class="rating">${f2(rawRating(x))}</div><div>${nf(x.goals)}</div><div>${nf(x.assists)}</div></div>`).join('');bindCards($('#rrows'))}
[['#cq',loadClubs,'c'],['#pq',loadPlayers,'p']].forEach(([id,fn,k])=>$(id).oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{state[k]=1;fn()},300)});['#cp','#cs'].forEach(id=>$(id).onchange=()=>{state.c=1;loadClubs()});['#pp','#ps'].forEach(id=>$(id).onchange=()=>{state.p=1;loadPlayers()});$('#mp').onchange=loadMatches;['#rp','#rm'].forEach(id=>$(id).onchange=loadRank);
function curveSvg(data){if(!data?.length)return '<div class="muted">Pas encore assez de matchs archivés.</div>';const W=620,H=210,pad=30,step=(W-pad*2)/Math.max(1,data.length-1),y=v=>H-pad-(Math.max(-4,Math.min(4,v))+4)/8*(H-pad*2),pts=data.map((x,i)=>`${pad+i*step},${y(x.gd)}`).join(' '),grid=[-4,-2,0,2,4].map(v=>`<line class="chartGrid" x1="${pad}" y1="${y(v)}" x2="${W-pad}" y2="${y(v)}"/><text class="chartText" x="4" y="${y(v)+4}">${v>0?'+':''}${v}</text>`).join(''),dots=data.map((x,i)=>`<circle class="chartDot" cx="${pad+i*step}" cy="${y(x.gd)}" r="5"><title>${esc(x.opponent)} ${x.gf}-${x.ga}</title></circle><text class="chartText" text-anchor="middle" x="${pad+i*step}" y="${H-5}">${esc((x.opponent||'?').slice(0,6))}</text>`).join('');return `<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Différence de buts sur les dix derniers matchs">${grid}<polyline class="chartLine" points="${pts}"/>${dots}</svg>`}
function pitchHtml(f){const by={FWD:[],MID:[],DEF:[],GK:[]};(f?.lineup||[]).forEach(x=>(by[x.role]||by.MID).push(x));const row=role=>`<div class="pitchRow">${(by[role]||[]).map(x=>`<div class="playerDot"><b>${esc(x.name)}</b><span>${x.rating?f2(x.rating):''}${x.signature_playstyle?' • '+esc(x.signature_playstyle):''}</span></div>`).join('')}</div>`;return `<div class="pitch"><div class="pitchRows">${row('FWD')}${row('MID')}${row('DEF')}${row('GK')}</div></div><div class="formationMeta"><b>${esc(f?.name||'—')}</b> • confiance ${Math.round((f?.confidence||0)*100)}% • ${nf(f?.sample||0)} matchs observés</div><div class="notice">${esc(f?.note||'La formation est une estimation.')}</div>`}
function rosterHtml(players){return `<div class="rosterTable"><div class="rosterRow th"><div>Joueur</div><div>Poste</div><div>Note</div><div>Matchs</div><div>G+A</div><div>Archetype</div><div>PlayStyles</div></div>${players.map(p=>{const extra=(p.playstyles||[]).filter(x=>x!==p.signature_playstyle).slice(0,4);return `<div class="rosterRow click" data-player="${esc(p.platform)}|${esc(p.player_id)}"><div><b>${esc(p.name)}</b><div class="muted">${nf(p.recent_apps||0)} apparitions archivées${p.overall?' • GEN '+nf(p.overall):''}</div></div><div><span class="tag">${esc(pos(p))}</span></div><div class="rating">${f2(rawRating(p))}</div><div>${nf(p.games)}</div><div>${nf(+p.goals + +p.assists)}</div><div>${esc(p.archetype_name||'—')}<div class="muted">${esc(p.signature_playstyle||'')}</div></div><div>${p.signature_playstyle?`<span class="ps">★ ${esc(p.signature_playstyle)}</span>`:''}${extra.map(x=>`<span class="ps">${esc(x)}</span>`).join('')||(!p.signature_playstyle?'<span class="muted">Non exposé par EA</span>':'')}</div></div>`}).join('')}</div>`}
async function openClub(p,id){$('#modalBg').classList.add('on');$('#mpill').textContent='Club FC26';$('#mtitle').textContent='Chargement…';$('#msub').textContent='';$('#mbody').innerHTML='<span class="loader"></span> Récupération des données…';try{const r=await get('/api/club?platform='+encodeURIComponent(p)+'&id='+encodeURIComponent(id)),c=r.club,t=+c.wins + +c.draws + +c.losses,w=t?Math.round(+c.wins/t*100):0;$('#mpill').textContent=c.platform_label;$('#mtitle').textContent=c.name;$('#msub').innerHTML=`ID ${esc(c.club_id)} • données FC26 <button class="refreshBtn" id="refreshClub">↻ Actualiser chez EA</button>`;$('#mbody').innerHTML=`<div class="detail"><div class="d"><b>${nf(c.skill)}</b><span>Skill</span></div><div class="d"><b>${nf(c.games)}</b><span>Matchs</span></div><div class="d"><b>${nf(c.wins)}</b><span>Victoires</span></div><div class="d"><b>${w}%</b><span>Ratio victoire</span></div><div class="d"><b>${nf(r.players.length)}</b><span>Joueurs connus</span></div></div><div class="clubDash"><div class="panel"><div class="panelHead"><h3>Courbe des 10 derniers matchs</h3><span class="muted">différence de buts</span></div><div class="curveWrap">${curveSvg(r.curve)}</div></div><div class="panel"><div class="panelHead"><h3>Composition la plus utilisée</h3><span class="tag">estimée</span></div>${pitchHtml(r.formation)}</div></div><div class="clubDash"><div class="panel"><h3>Derniers adversaires</h3><div class="opponents">${(r.opponents||[]).map(o=>`<div class="opp"><div><b>${esc(o.name||'—')}</b><div class="muted">${datetime(o.ts)}</div></div><div><span class="result ${o.result}">${o.result}</span> <b>${esc(o.score)}</b></div></div>`).join('')||'<div class="muted">Aucun adversaire archivé.</div>'}</div></div><div class="panel"><h3>20 derniers matchs archivés</h3>${(r.matches||[]).slice(0,20).map(m=>matchHtml(m,c.club_id)).join('')||'<div class="muted">Aucun match.</div>'}</div></div><h3 class="subTitle">Effectif et profils joueurs</h3>${rosterHtml(r.players)}`;bindCards($('#mbody'));$('#refreshClub').onclick=async()=>{const b=$('#refreshClub');b.disabled=true;b.innerHTML='<span class="loader"></span> EA…';try{await get('/api/club/refresh?platform='+encodeURIComponent(p)+'&id='+encodeURIComponent(id)+'&name='+encodeURIComponent(c.name),{method:'POST'});await openClub(p,id);dash()}catch(e){alert(e.message);b.disabled=false}}}catch(e){$('#mtitle').textContent='Erreur';$('#mbody').innerHTML='<div class="notice">'+esc(e.message)+'</div>'}}
async function openPlayer(p,id){$('#modalBg').classList.add('on');$('#mpill').textContent='Joueur';$('#mtitle').textContent='Chargement…';$('#msub').textContent='';$('#mbody').innerHTML='<span class="loader"></span>';try{const r=await get('/api/player?platform='+encodeURIComponent(p)+'&id='+encodeURIComponent(id)),x=r.player;$('#mpill').textContent=x.platform_label;$('#mtitle').textContent=x.name;$('#msub').textContent=x.club_name||'Club inconnu';const extra=(x.playstyles||[]).filter(y=>y!==x.signature_playstyle);$('#mbody').innerHTML=`<div class="detail"><div class="d"><b class="rating">${f2(rawRating(x))}</b><span>Note moyenne</span></div><div class="d"><b>${nf(x.overall)}</b><span>GEN</span></div><div class="d"><b>${nf(x.games)}</b><span>Matchs</span></div><div class="d"><b>${nf(x.goals)}</b><span>Buts</span></div><div class="d"><b>${nf(x.assists)}</b><span>Passes</span></div></div><div class="homeGrid"><div class="panel"><h3>Profil</h3><div class="line"><span>Poste</span><b>${esc(pos(x))}</b></div><div class="line"><span>Archetype</span><b>${esc(x.archetype_name||'—')}</b></div><div class="line"><span>Signature PlayStyle</span><b>${esc(x.signature_playstyle||'—')}</b></div><div class="line"><span>Buts / match</span><b>${f2(x.gpg)}</b></div><div class="line"><span>Passes / match</span><b>${f2(x.apg)}</b></div><div>${x.signature_playstyle?`<span class="ps">★ ${esc(x.signature_playstyle)}</span>`:''}${extra.map(z=>`<span class="ps">${esc(z)}</span>`).join('')}</div></div><div class="panel"><h3>Dernières performances</h3>${(r.recent||[]).slice(0,10).map(a=>`<div class="line"><div><b>${esc(a.position||'Poste inconnu')}</b><div class="muted">${datetime(a.ts)} • ${esc(a.home_name)} ${nf(a.home_goals)}-${nf(a.away_goals)} ${esc(a.away_name)}</div></div><span class="rating">${f2(a.rating)}</span></div>`).join('')||'<div class="muted">Aucune performance individuelle archivée.</div>'}</div></div>`}catch(e){$('#mtitle').textContent='Erreur';$('#mbody').innerHTML='<div class="notice">'+esc(e.message)+'</div>'}}
$('#close').onclick=()=>$('#modalBg').classList.remove('on');$('#modalBg').onclick=e=>e.target===$('#modalBg')&&$('#modalBg').classList.remove('on');document.addEventListener('keydown',e=>e.key==='Escape'&&$('#modalBg').classList.remove('on'));
window.openClub=openClub;window.openPlayer=openPlayer;dash();overview();setInterval(dash,15000);
