import{nf,esc,labels,dateTime}from'./v8-common.js';
const $=s=>document.querySelector(s),state={pp:1,cp:1,limit:50,pt:1,ct:1};
async function get(url){const r=await fetch(url),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erreur serveur');return d}
async function summary(){const r=await get('/api/archive/fc26/summary');$('#aPlayers').textContent=nf(r.players);$('#aClubs').textContent=nf(r.clubs);$('#aMatches').textContent=nf(r.matches);$('#aApps').textContent=nf(r.appearances)}
function playerRow(p){return`<div class="archiveRow"><div><b>${esc(p.name)}</b><div class="muted">${esc(labels[p.platform]||p.platform||'')}</div></div><div>${esc(p.club_name||'Sans club')}</div><div>${nf(p.games)} matchs</div><div>${nf(p.goals)} buts</div><div>${nf(p.assists)} passes</div><div>${Number(p.rating||0)>0?Number(p.rating).toFixed(2):'—'}</div></div>`}
function clubRow(c){const g=Number(c.games||0),wr=g?Number(c.wins||0)/g*100:0;return`<div class="archiveRow"><div><b>${esc(c.name)}</b><div class="muted">${esc(labels[c.platform]||c.platform||'')}</div></div><div>ID ${esc(c.club_id)}</div><div>${nf(c.games)} matchs</div><div>${nf(c.wins)} V</div><div>${nf(c.draws)} N</div><div>${wr?wr.toFixed(1)+'%':'—'}</div></div>`}
async function players(){const q=$('#playerQ').value.trim(),p=$('#playerPlatform').value,r=await get(`/api/archive/fc26/players?q=${encodeURIComponent(q)}&platform=${encodeURIComponent(p)}&page=${state.pp}&limit=${state.limit}`);state.pt=Math.max(1,Math.ceil(r.total/state.limit));$('#players').innerHTML='<div class="archiveTable"><div class="archiveRow head"><div>Joueur</div><div>Club</div><div>Matchs</div><div>Buts</div><div>Passes</div><div>Note</div></div>'+((r.items||[]).map(playerRow).join('')||'<div class="empty">Aucun joueur trouvé.</div>')+'</div>';$('#pInfo').textContent=`Page ${state.pp}/${state.pt} • ${nf(r.total)} joueurs`;$('#pPrev').disabled=state.pp<=1;$('#pNext').disabled=state.pp>=state.pt}
async function clubs(){const q=$('#clubQ').value.trim(),p=$('#clubPlatform').value,r=await get(`/api/archive/fc26/clubs?q=${encodeURIComponent(q)}&platform=${encodeURIComponent(p)}&page=${state.cp}&limit=${state.limit}`);state.ct=Math.max(1,Math.ceil(r.total/state.limit));$('#clubs').innerHTML='<div class="archiveTable"><div class="archiveRow head"><div>Club</div><div>ID</div><div>Matchs</div><div>V</div><div>N</div><div>% V</div></div>'+((r.items||[]).map(clubRow).join('')||'<div class="empty">Aucun club trouvé.</div>')+'</div>';$('#cInfo').textContent=`Page ${state.cp}/${state.ct} • ${nf(r.total)} clubs`;$('#cPrev').disabled=state.cp<=1;$('#cNext').disabled=state.cp>=state.ct}
async function matches(){const r=await get('/api/archive/fc26/matches?limit=80');$('#matches').innerHTML=(r.items||[]).map(m=>`<div class="archiveRow match"><b>${esc(m.home_name||'—')}</b><strong>${nf(m.home_goals)}-${nf(m.away_goals)}</strong><b>${esc(m.away_name||'—')}</b><span class="muted">${dateTime(m.ts)}</span></div>`).join('')||'<div class="empty">Aucun match archivé.</div>'}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));const t=b.dataset.tab;$('#playersPanel').hidden=t!=='players';$('#clubsPanel').hidden=t!=='clubs';$('#matchesPanel').hidden=t!=='matches';if(t==='matches')matches()});
let timer;$('#playerQ').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{state.pp=1;players()},180)};$('#playerPlatform').onchange=()=>{state.pp=1;players()};$('#clubQ').oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>{state.cp=1;clubs()},180)};$('#clubPlatform').onchange=()=>{state.cp=1;clubs()};$('#pPrev').onclick=()=>{if(state.pp>1){state.pp--;players()}};$('#pNext').onclick=()=>{if(state.pp<state.pt){state.pp++;players()}};$('#cPrev').onclick=()=>{if(state.cp>1){state.cp--;clubs()}};$('#cNext').onclick=()=>{if(state.cp<state.ct){state.cp++;clubs()}};
Promise.all([summary(),players(),clubs()]).catch(e=>console.error(e));