import{$,esc,nf,labels,initials,clubUrl,get}from'./v8-common.js';
const state={page:1,pages:1,total:0,limit:50,timer:null,sort:'skill',dir:'desc'};
const textSorts=new Set(['name','platform']);
function arrow(key){if(state.sort!==key)return'↕';return state.dir==='desc'?'↓':'↑'}
function sortButton(label,key){const active=state.sort===key?' active':'';return`<button class="sortBtn${active}" data-sort="${key}" aria-label="Trier par ${esc(label)}">${esc(label)} <span>${arrow(key)}</span></button>`}
function renderHead(){const h=$('#head');h.innerHTML=`<div class="rank">#</div><div class="identity">${sortButton('Club','name')}</div><div>${sortButton('Plateforme','platform')}</div><div class="num">${sortButton('Skill','skill')}</div><div class="num">${sortButton('Matchs','games')}</div><div class="num">${sortButton('V','wins')}</div><div class="num">${sortButton('N','draws')}</div><div class="num">${sortButton('D','losses')}</div><div class="num">${sortButton('% V','winrate')}</div>`;h.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const k=b.dataset.sort;if(state.sort===k)state.dir=state.dir==='desc'?'asc':'desc';else{state.sort=k;state.dir=textSorts.has(k)?'asc':'desc'}state.page=1;load()})}
function setUrl(){const u=new URL(location.href),q=$('#search').value.trim(),p=$('#platform').value;if(q)u.searchParams.set('q',q);else u.searchParams.delete('q');if(p)u.searchParams.set('platform',p);else u.searchParams.delete('platform');if(state.sort!=='skill'||state.dir!=='desc'){u.searchParams.set('sort',state.sort);u.searchParams.set('dir',state.dir)}else{u.searchParams.delete('sort');u.searchParams.delete('dir')}if(state.page>1)u.searchParams.set('page',state.page);else u.searchParams.delete('page');history.replaceState(null,'',u)}
function row(c,i){const idx=(state.page-1)*state.limit+i+1,g=Number(c.games||0),wr=g?Number(c.wins||0)/g*100:0;return`<div class="row" data-url="${clubUrl(c)}"><div class="rank">${nf(idx)}</div><div class="identity"><div class="crest">${esc(initials(c.name))}</div><div class="who"><b>${esc(c.name)}</b><span>ID ${esc(c.club_id)}</span></div></div><div>${esc(labels[c.platform]||c.platform||'')}</div><div class="num skill">${nf(c.skill)}</div><div class="num">${nf(c.games)}</div><div class="num">${nf(c.wins)}</div><div class="num">${nf(c.draws)}</div><div class="num">${nf(c.losses)}</div><div class="num wr">${g?wr.toFixed(1)+'%':'—'}</div></div>`}
function pages(){const box=$('#pages');box.innerHTML='';if(state.pages<=1){$('#prev').disabled=true;$('#next').disabled=true;return}const start=Math.max(1,state.page-2),end=Math.min(state.pages,start+4);for(let p=start;p<=end;p++){const b=document.createElement('button');b.className='pagebtn'+(p===state.page?' active':'');b.textContent=p;b.onclick=()=>{state.page=p;load();scrollTo({top:0,behavior:'smooth'})};box.appendChild(b)}$('#prev').disabled=state.page<=1;$('#next').disabled=state.page>=state.pages}
async function load(){setUrl();renderHead();$('#rows').innerHTML='<div class="empty">Chargement des clubs…</div>';try{const q=$('#search').value.trim(),platform=$('#platform').value,sort=`${state.sort}:${state.dir}`,r=await get(`/api/clubs?q=${encodeURIComponent(q)}&platform=${encodeURIComponent(platform)}&sort=${encodeURIComponent(sort)}&page=${state.page}&limit=${state.limit}`);state.total=r.total||0;state.pages=r.pages||1;$('#clubCount').textContent=nf(state.total);$('#resultText').textContent=q?`${nf(state.total)} résultat${state.total>1?'s':''} pour « ${q} »`:`${nf(state.total)} clubs dans la base`;$('#rows').innerHTML=(r.items||[]).map(row).join('');$('#empty').hidden=(r.items||[]).length>0;pages();document.querySelectorAll('[data-url]').forEach(x=>x.onclick=()=>location.href=x.dataset.url)}catch(e){$('#rows').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
$('#search').oninput=()=>{clearTimeout(state.timer);state.timer=setTimeout(()=>{state.page=1;load()},220)};$('#platform').onchange=()=>{state.page=1;load()};$('#prev').onclick=()=>{if(state.page>1){state.page--;load()}};$('#next').onclick=()=>{if(state.page<state.pages){state.page++;load()}};
const params=new URLSearchParams(location.search);$('#search').value=params.get('q')||'';$('#platform').value=params.get('platform')||'';state.sort=params.get('sort')||'skill';state.dir=params.get('dir')==='asc'?'asc':'desc';state.page=Math.max(1,Number(params.get('page')||1));load();