import {Store} from './store5.js';
import {ea,extractClubs,syncClub} from './crawler5.js';
import {sleep,gap,num} from './constants.js';

const PLATFORM='common-gen5';
const INTERVAL_MINUTES=Math.max(8,Number(process.env.GROWTH_INTERVAL_MINUTES||10));
const QUERY_BATCH=Math.max(8,Number(process.env.GROWTH_QUERY_BATCH||28));
const HYDRATE_BATCH=Math.max(4,Number(process.env.GROWTH_HYDRATE_BATCH||14));
const CURATED=['team','united','city','real','club','proclub','esports','gaming','football','academy','elite','stars','legend','world','royal','athletic','sporting','olympic','racing','inter','dynamo','galaxy','wolves','lions','eagles','paris','france','london','madrid','italia','spain','germany','belgium','portugal','brazil','ajax','boys','red','blue','black','white','north','south','west','east'];
const state={running:false,queries:0,hits:0,newClubs:0,hydrated:0,newPlayers:0,lastQuery:'',lastError:'',started:0};
const cleanToken=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'').slice(0,18);

async function addQuery(store,q,priority=30){q=cleanToken(q);if(q.length<3)return;await store.pool.query(`INSERT INTO growth_queries(platform,query,last_run,hits,priority,state) VALUES($1,$2,0,0,$3,'pending') ON CONFLICT(platform,query) DO UPDATE SET priority=GREATEST(growth_queries.priority,EXCLUDED.priority),state=CASE WHEN growth_queries.state='skipped' THEN growth_queries.state ELSE 'pending' END`,[PLATFORM,q,priority])}
async function seedQueries(store){for(const q of CURATED)await addQuery(store,q,100)}
async function harvestClubNameQueries(store){const rows=await store.q(`SELECT name FROM clubs WHERE platform=$1 AND name<>'' ORDER BY updated_at DESC LIMIT 1600`,[PLATFORM]);const seen=new Set();for(const row of rows){const raw=String(row.name||''),words=raw.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().split(/[^a-z0-9]+/).filter(Boolean);for(const w of words){const t=cleanToken(w);if(t.length>=3&&!seen.has(t)){seen.add(t);await addQuery(store,t,45)}}const full=cleanToken(raw);for(const len of[3,4,5,6])if(full.length>=len){const t=full.slice(0,len);if(!seen.has(t)){seen.add(t);await addQuery(store,t,25)}}}return seen.size}
async function refreshLeaderboards(store){let found=0;for(const endpoint of['/currentSeasonLeaderboard']){try{found+=(await extractClubs(store,await ea(endpoint,{platform:PLATFORM,maxResultCount:100}),PLATFORM)).length}catch(e){state.lastError=e.message}await sleep(gap())}return found}
async function searchQuery(store,row){const ids=new Set();let errors=0;for(const endpoint of['/currentSeasonLeaderboard/search']){try{const clubs=await extractClubs(store,await ea(endpoint,{platform:PLATFORM,clubName:row.query,maxResultCount:100}),PLATFORM);for(const c of clubs)ids.add(String(c.id))}catch(e){state.lastError=e.message;errors++}await sleep(gap())}const hits=ids.size,nextPriority=hits>=60?140:hits>=30?110:hits>=10?80:hits>0?60:Math.max(5,num(row.priority)-10),nextState=errors===2&&/EA 400/.test(state.lastError||'')?'skipped':'pending';await store.pool.query(`UPDATE growth_queries SET last_run=EXTRACT(EPOCH FROM NOW())::BIGINT,hits=$1,priority=$2,state=$3 WHERE platform=$4 AND query=$5`,[hits,nextPriority,nextState,PLATFORM,row.query]);state.queries++;state.hits+=hits;state.lastQuery=row.query;return hits}
async function hydrate(store){const rows=await store.q(`
  SELECT c.platform,c.club_id,c.name,c.synced_at,COUNT(DISTINCT p.uid) player_count,COALESCE(MAX(m.ts),0) latest_match
  FROM clubs c
  LEFT JOIN players p ON p.platform=c.platform AND p.club_id=c.club_id
  LEFT JOIN matches m ON m.platform=c.platform AND (m.home_club_id=c.club_id OR m.away_club_id=c.club_id)
  WHERE c.platform=$1 AND c.club_id ~ '^[0-9]+
  GROUP BY c.platform,c.club_id,c.name,c.synced_at,c.updated_at
  HAVING COALESCE(c.synced_at,0)=0 OR COUNT(DISTINCT p.uid)=0
  ORDER BY CASE WHEN COUNT(DISTINCT p.uid)=0 THEN 0 ELSE 1 END,CASE WHEN COALESCE(MAX(m.ts),0)>0 THEN 0 ELSE 1 END,COALESCE(MAX(m.ts),0) DESC,c.updated_at DESC
  LIMIT $2`,[PLATFORM,HYDRATE_BATCH]);
  for(const club of rows){const before=num((await store.one(`SELECT COUNT(*) c FROM players WHERE platform=$1`,[PLATFORM]))?.c);try{await syncClub(store,{club_id:club.club_id,name:club.name},PLATFORM);const after=num((await store.one(`SELECT COUNT(*) c FROM players WHERE platform=$1`,[PLATFORM]))?.c);state.hydrated++;state.newPlayers+=Math.max(0,after-before);console.log(`[GROWTH18] hydrated ${club.name} (${club.club_id}) players+${Math.max(0,after-before)}`)}catch(e){state.lastError=e.message;console.warn(`[GROWTH18 hydrate] ${club.club_id}: ${e.message}`)}await sleep(gap())}}
async function cycle(store){if(store.mode!=='postgres'||state.running)return;state.running=true;Object.assign(state,{queries:0,hits:0,newClubs:0,hydrated:0,newPlayers:0,lastQuery:'',lastError:'',started:Math.floor(Date.now()/1000)});try{const beforeClubs=num((await store.one('SELECT COUNT(*) c FROM clubs'))?.c),beforePlayers=num((await store.one('SELECT COUNT(*) c FROM players'))?.c),topHits=await refreshLeaderboards(store);await harvestClubNameQueries(store);const rows=await store.q(`SELECT query,priority,last_run,hits FROM growth_queries WHERE platform=$1 AND state='pending' ORDER BY CASE WHEN last_run=0 THEN 0 ELSE 1 END,last_run ASC,priority DESC,hits DESC LIMIT $2`,[PLATFORM,QUERY_BATCH]);console.log(`[GROWTH18] cycle start clubs=${beforeClubs} players=${beforePlayers} queries=${rows.length} leaderboardHits=${topHits}`);for(const row of rows){await searchQuery(store,row);await sleep(gap())}await harvestClubNameQueries(store);const midClubs=num((await store.one('SELECT COUNT(*) c FROM clubs'))?.c);state.newClubs=Math.max(0,midClubs-beforeClubs);await hydrate(store);const afterClubs=num((await store.one('SELECT COUNT(*) c FROM clubs'))?.c),afterPlayers=num((await store.one('SELECT COUNT(*) c FROM players'))?.c),q=await store.one(`SELECT COUNT(*) total,COUNT(*) FILTER(WHERE state='pending') pending,COUNT(*) FILTER(WHERE state='skipped') skipped FROM growth_queries WHERE platform=$1`,[PLATFORM]);console.log(`[GROWTH18] done queries=${state.queries} hits=${state.hits} clubs=${beforeClubs}->${afterClubs} players=${beforePlayers}->${afterPlayers} hydrated=${state.hydrated} queue=${num(q?.pending)}${state.lastError?' lastError='+state.lastError:''}`)}finally{state.running=false}}

const previousInit=Store.prototype.init;
Store.prototype.init=async function(){await previousInit.call(this);if(this.mode!=='postgres')return;await this.pool.query(`CREATE TABLE IF NOT EXISTS growth_queries(platform TEXT NOT NULL,query TEXT NOT NULL,last_run BIGINT DEFAULT 0,hits INTEGER DEFAULT 0,priority INTEGER DEFAULT 0,state TEXT DEFAULT 'pending',PRIMARY KEY(platform,query))`);await this.pool.query(`CREATE INDEX IF NOT EXISTS growth_queries_run_idx ON growth_queries(platform,state,last_run,priority)`);const q=await this.one(`SELECT COUNT(*) total,COUNT(*) FILTER(WHERE state='pending') pending FROM growth_queries WHERE platform=$1`,[PLATFORM]);console.log(`[GROWTH18] startup ready queries=${num(q?.total)} pending=${num(q?.pending)}; heavy seeding deferred`);setTimeout(async()=>{try{await seedQueries(this);await harvestClubNameQueries(this);await cycle(this)}catch(e){console.warn('[GROWTH18]',e.message)}},5000).unref();setInterval(()=>cycle(this).catch(e=>console.warn('[GROWTH18]',e.message)),INTERVAL_MINUTES*60000).unref()};

const prevDashboard=Store.prototype.dashboard;
Store.prototype.dashboard=async function(){const d=await prevDashboard.call(this);if(this.mode!=='postgres')return d;let q={total:0,pending:0,hits:0};try{q=await this.one(`SELECT COUNT(*) total,COUNT(*) FILTER(WHERE state='pending') pending,COALESCE(SUM(hits),0) hits FROM growth_queries WHERE platform=$1`,[PLATFORM])||q}catch(e){if(e?.code!=='42P01')console.warn('[GROWTH18 dashboard]',e.message)}return{...d,growthEngine:{...state,queryTotal:num(q?.total),queryPending:num(q?.pending),queryHits:num(q?.hits),intervalMinutes:INTERVAL_MINUTES,hydrateBatch:HYDRATE_BATCH}}};
console.log('[GROWTH18] club graph expansion and automatic player hydration enabled');
 AND (COALESCE(c.synced_at,0)=0 OR COALESCE(c.synced_at,0)<EXTRACT(EPOCH FROM NOW()-INTERVAL '24 hours'))
  GROUP BY c.platform,c.club_id,c.name,c.synced_at,c.updated_at
  HAVING COALESCE(c.synced_at,0)=0 OR COUNT(DISTINCT p.uid)=0
  ORDER BY CASE WHEN COUNT(DISTINCT p.uid)=0 THEN 0 ELSE 1 END,CASE WHEN COALESCE(MAX(m.ts),0)>0 THEN 0 ELSE 1 END,COALESCE(MAX(m.ts),0) DESC,c.updated_at DESC
  LIMIT $2`,[PLATFORM,HYDRATE_BATCH]);
  for(const club of rows){const before=num((await store.one(`SELECT COUNT(*) c FROM players WHERE platform=$1`,[PLATFORM]))?.c);try{await syncClub(store,{club_id:club.club_id,name:club.name},PLATFORM);const after=num((await store.one(`SELECT COUNT(*) c FROM players WHERE platform=$1`,[PLATFORM]))?.c);state.hydrated++;state.newPlayers+=Math.max(0,after-before);console.log(`[GROWTH18] hydrated ${club.name} (${club.club_id}) players+${Math.max(0,after-before)}`)}catch(e){state.lastError=e.message;console.warn(`[GROWTH18 hydrate] ${club.club_id}: ${e.message}`)}await sleep(gap())}}
async function cycle(store){if(store.mode!=='postgres'||state.running)return;state.running=true;Object.assign(state,{queries:0,hits:0,newClubs:0,hydrated:0,newPlayers:0,lastQuery:'',lastError:'',started:Math.floor(Date.now()/1000)});try{const beforeClubs=num((await store.one('SELECT COUNT(*) c FROM clubs'))?.c),beforePlayers=num((await store.one('SELECT COUNT(*) c FROM players'))?.c),topHits=await refreshLeaderboards(store);await harvestClubNameQueries(store);const rows=await store.q(`SELECT query,priority,last_run,hits FROM growth_queries WHERE platform=$1 AND state='pending' ORDER BY CASE WHEN last_run=0 THEN 0 ELSE 1 END,last_run ASC,priority DESC,hits DESC LIMIT $2`,[PLATFORM,QUERY_BATCH]);console.log(`[GROWTH18] cycle start clubs=${beforeClubs} players=${beforePlayers} queries=${rows.length} leaderboardHits=${topHits}`);for(const row of rows){await searchQuery(store,row);await sleep(gap())}await harvestClubNameQueries(store);const midClubs=num((await store.one('SELECT COUNT(*) c FROM clubs'))?.c);state.newClubs=Math.max(0,midClubs-beforeClubs);await hydrate(store);const afterClubs=num((await store.one('SELECT COUNT(*) c FROM clubs'))?.c),afterPlayers=num((await store.one('SELECT COUNT(*) c FROM players'))?.c),q=await store.one(`SELECT COUNT(*) total,COUNT(*) FILTER(WHERE state='pending') pending,COUNT(*) FILTER(WHERE state='skipped') skipped FROM growth_queries WHERE platform=$1`,[PLATFORM]);console.log(`[GROWTH18] done queries=${state.queries} hits=${state.hits} clubs=${beforeClubs}->${afterClubs} players=${beforePlayers}->${afterPlayers} hydrated=${state.hydrated} queue=${num(q?.pending)}${state.lastError?' lastError='+state.lastError:''}`)}finally{state.running=false}}

const previousInit=Store.prototype.init;
Store.prototype.init=async function(){await previousInit.call(this);if(this.mode!=='postgres')return;await this.pool.query(`CREATE TABLE IF NOT EXISTS growth_queries(platform TEXT NOT NULL,query TEXT NOT NULL,last_run BIGINT DEFAULT 0,hits INTEGER DEFAULT 0,priority INTEGER DEFAULT 0,state TEXT DEFAULT 'pending',PRIMARY KEY(platform,query))`);await this.pool.query(`CREATE INDEX IF NOT EXISTS growth_queries_run_idx ON growth_queries(platform,state,last_run,priority)`);const q=await this.one(`SELECT COUNT(*) total,COUNT(*) FILTER(WHERE state='pending') pending FROM growth_queries WHERE platform=$1`,[PLATFORM]);console.log(`[GROWTH18] startup ready queries=${num(q?.total)} pending=${num(q?.pending)}; heavy seeding deferred`);setTimeout(async()=>{try{await seedQueries(this);await harvestClubNameQueries(this);await cycle(this)}catch(e){console.warn('[GROWTH18]',e.message)}},5000).unref();setInterval(()=>cycle(this).catch(e=>console.warn('[GROWTH18]',e.message)),INTERVAL_MINUTES*60000).unref()};

const prevDashboard=Store.prototype.dashboard;
Store.prototype.dashboard=async function(){const d=await prevDashboard.call(this);if(this.mode!=='postgres')return d;let q={total:0,pending:0,hits:0};try{q=await this.one(`SELECT COUNT(*) total,COUNT(*) FILTER(WHERE state='pending') pending,COALESCE(SUM(hits),0) hits FROM growth_queries WHERE platform=$1`,[PLATFORM])||q}catch(e){if(e?.code!=='42P01')console.warn('[GROWTH18 dashboard]',e.message)}return{...d,growthEngine:{...state,queryTotal:num(q?.total),queryPending:num(q?.pending),queryHits:num(q?.hits),intervalMinutes:INTERVAL_MINUTES,hydrateBatch:HYDRATE_BATCH}}};
console.log('[GROWTH18] club graph expansion and automatic player hydration enabled');
