import{$,esc,nf,f2,labels,initials,playerUrl,get}from'./v8-common.js';
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function fastGet(url){let last;for(let i=0;i<4;i++){try{return await get(url)}catch(e){last=e;if(i<3)await wait(550*(i+1))}}throw last}
const state={page:1,pages:1,total:0,limit:50,timer:null,sort:'games',dir:'desc'};
const textSorts=new Set(['name','club','position']);
const archetypeNames={'1':'Shot Stopper','2':'Sweeper Keeper','3':'Progressor','4':'Boss','5':'Engine','6':'Marauder','7':'Recycler','8':'Maestro','9':'Creator','10':'Spark','11':'Magician','12':'Finisher','13':'Target'};
function archetype(p){if(p.archetype_name)return p.archetype_name;try{const r=JSON.parse(p.raw_json||'{}'),id=String(r.archetypeid??r.archetypeId??r.archetype_id??r.buildId??'');return archetypeNames[id]||'—'}catch{return'—'}}
function rawRating(p){if(+p.rating>0)return+p.rating;try{const r=JSON.parse(p.raw_json||'{}'),v=Number(r.ratingAve??r.rating??0);return v>10&&v<=100?v/10:v}catch{return 0}}
function pos(p){return p.position||p.recent_role||'—'}
function arrow(key){if(state.sort!==key)return'↕';return state.dir==='desc'?'↓':'↑'}
function sortButton(label,key){const active=state.sort===key?' active':'';return`<button class="sortBtn${active}" data-sort="${key}" aria-label="Trier par ${esc(label)}">${esc(label)} <span>${arrow(key)}</span></button>`}
function renderHead(){const h=$('#head');h.innerHTML=`<div class="rank">#</div><div class="identity">${sortButton('Joueur','name')}</div><div>${sortButton('Club','club')}</div><div>${sortButton('Poste','position')}</div><div class="num">${sortButton('Note','rating')}</div><div class="num">${sortButton('Matchs','games')}</div><div class="num">${sortButton('Buts','goals')}</div><div class="num">${sortButton('Passes','assists')}</div><div class="num">${sortButton('B+P','contributions')}</div>`;h.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const k=b.dataset.sort;if(state.sort===k)state.dir=state.dir==='desc'?'asc':'desc';else{state.sort=k;state.dir=textSorts.has(k)?'asc':'desc'}state.page=1;load()})}
const val=id=>$(id)?.value?.trim?.()??'';
function optionText(id){const e=$(id);return e?.selectedOptions?.[0]?.textContent?.trim()||''}
function filterSpec(){const parts=[`${state.sort}:${state.dir}`],add=(k,v)=>{if(v&&v!=='0')parts.push(`${k}=${v}`)};add('pos',val('#position'));add('mg',val('#minGames'));add('mr',val('#minRating'));add('mb',val('#minGoals'));add('ma',val('#minAssists'));add('club',val('#clubFilter'));add('ad',val('#activeDays'));return parts.join('|')}
function renderActiveFilters(){const box=$('#activeFilters');if(!box)return;const chips=[],add=(id,text)=>{const v=val(id);if(v&&v!=='0')chips.push(`<button class="filterChip" data-clear="${id}">${esc(text)} <b>×</b></button>`)};add('#search',`Recherche : ${val('#search')}`);if(val('#platform'))add('#platform',optionText('#platform'));if(val('#position'))add('#position',optionText('#position'));if(val('#minGames'))add('#minGames',`Matchs ≥ ${val('#minGames')}`);if(val('#minRating'))add('#minRating',`Note ≥ ${val('#minRating')}`);if(val('#minGoals'))add('#minGoals',`Buts ≥ ${val('#minGoals')}`);if(val('#minAssists'))add('#minAssists',`Passes ≥ ${val('#minAssists')}`);if(val('#clubFilter'))add('#clubFilter',`Club : ${val('#clubFilter')}`);if(val('#activeDays')&&val('#activeDays')!=='0')add('#activeDays',optionText('#activeDays'));box.innerHTML=chips.length?`<span class="filterLabel">Filtres actifs</span>${chips.join('')}`:'';box.querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{const el=$(b.dataset.clear);if(!el)return;el.value=b.dataset.clear==='#activeDays'?'0':'';state.page=1;load()})}
function setUrl(){const u=new URL(location.href),map=[['q',val('#search')],['platform',val('#platform')],['position',val('#position')],['minGames',val('#minGames')],['minRating',val('#minRating')],['minGoals',val('#minGoals')],['minAssists',val('#minAssists')],['club',val('#clubFilter')],['activeDays',val('#activeDays')]];for(const[k,v]of map){if(v&&v!=='0')u.searchParams.set(k,v);else u.searchParams.delete(k)}if(state.sort!=='games'||state.dir!=='desc'){u.searchParams.set('sort',state.sort);u.searchParams.set('dir',state.dir)}else{u.searchParams.delete('sort');u.searchParams.delete('dir')}if(state.limit!==50)u.searchParams.set('limit',String(state.limit));else u.searchParams.delete('limit');if(state.page>1)u.searchParams.set('page',state.page);else u.searchParams.delete('page');history.replaceState(null,'',u)}
function playerRow(p,i){const r=rawRating(p),ga=Number(p.goals||0)+Number(p.assists||0),idx=(state.page-1)*state.limit+i+1;return`<div class="row" data-url="${playerUrl(p)}"><div class="rank">${nf(idx)}</div><div class="identity"><div class="avatar" style="font-size:9px;line-height:1.05;text-align:center;padding:4px">${esc(archetype(p))}</div><div class="who"><b>${esc(p.name)}</b></div></div><div class="club"><b>${esc(p.club_name||'Club inconnu')}</b><span>${p.club_id?`ID ${esc(p.club_id)}`:'—'}</span></div><div><span class="pos">${esc(pos(p))}</span></div><div class="num rating">${f2(r)}</div><div class="num">${nf(p.games)}</div><div class="num">${nf(p.goals)}</div><div class="num">${nf(p.assists)}</div><div class="num ga">${nf(ga)}</div></div>`}
function renderPages(){const box=$('#pages');box.innerHTML='';if(state.pages<=1){$('#prev').disabled=true;$('#next').disabled=true;return}const start=Math.max(1,state.page-2),end=Math.min(state.pages,start+4);for(let p=start;p<=end;p++){const b=document.createElement('button');b.className='pagebtn'+(p===state.page?' active':'');b.textContent=p;b.onclick=()=>{state.page=p;load();scrollTo({top:0,behavior:'smooth'})};box.appendChild(b)}$('#prev').disabled=state.page<=1;$('#next').disabled=state.page>=state.pages}
function bindRows(){document.querySelectorAll('#rows [data-url]').forEach(x=>{x.tabIndex=0;x.setAttribute('role','link');x.setAttribute('aria-label',`Ouvrir ${x.querySelector('.who b')?.textContent||'le joueur'}`);x.onclick=()=>location.href=x.dataset.url;x.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();location.href=x.dataset.url}}})}
function injectAccessibilityStyle(){if(document.getElementById('directory-a11y-style'))return;const s=document.createElement('style');s.id='directory-a11y-style';s.textContent='.tbody .row[role="link"]{cursor:pointer}.tbody .row[role="link"]:focus-visible{outline:2px solid #c084fc!important;outline-offset:2px!important;box-shadow:0 0 0 4px #7c3aed33,0 16px 38px #0006!important}.tablewrap[aria-busy="true"]{opacity:.78;transition:opacity .15s}.tablewrap[aria-busy="false"]{opacity:1;transition:opacity .15s}';document.head.appendChild(s)}
async function load(){setUrl();renderHead();renderActiveFilters();const table=document.querySelector('.tablewrap');table?.setAttribute('aria-busy','true');$('#rows').innerHTML='<div class="empty">Chargement des joueurs…</div>';$('#empty').hidden=true;try{const q=val('#search'),platform=val('#platform'),r=await fastGet(`/api/players?q=${encodeURIComponent(q)}&platform=${encodeURIComponent(platform)}&sort=${encodeURIComponent(filterSpec())}&page=${state.page}&limit=${state.limit}`);state.total=r.total||0;state.pages=r.pages||1;if(state.page>state.pages&&state.pages>0){state.page=state.pages;return load()}$('#playerCount').textContent=nf(state.total);const filtered=['#position','#minGames','#minRating','#minGoals','#minAssists','#clubFilter','#activeDays'].some(x=>val(x)&&val(x)!=='0');$('#resultText').textContent=q?`${nf(state.total)} résultat${state.total>1?'s':''} pour « ${q} »`:filtered?`${nf(state.total)} joueurs correspondent aux filtres`:`${nf(state.total)} joueurs dans la base`;$('#rows').innerHTML=(r.items||[]).map(playerRow).join('');$('#empty').hidden=(r.items||[]).length>0;renderPages();bindRows()}catch(e){$('#rows').innerHTML=`<div class="empty">${esc(e.message)}</div>`}finally{table?.setAttribute('aria-busy','false')}}
function schedule(){clearTimeout(state.timer);state.timer=setTimeout(()=>{state.page=1;load()},180)}
$('#search').oninput=schedule;$('#platform').onchange=schedule;for(const id of['#position','#minGames','#minRating','#minGoals','#minAssists','#clubFilter','#activeDays']){const el=$(id);if(el){el.oninput=schedule;el.onchange=schedule}}
$('#pageSize').onchange=()=>{state.limit=[25,50,100].includes(Number($('#pageSize').value))?Number($('#pageSize').value):50;state.page=1;load()};
$('#resetFilters').onclick=()=>{for(const id of['#position','#minGames','#minRating','#minGoals','#minAssists','#clubFilter','#activeDays']){const el=$(id);if(el)el.value=id==='#activeDays'?'0':''}$('#search').value='';$('#platform').value='';state.page=1;load()};$('#prev').onclick=()=>{if(state.page>1){state.page--;load()}};$('#next').onclick=()=>{if(state.page<state.pages){state.page++;load()}};
document.addEventListener('keydown',e=>{const tag=document.activeElement?.tagName?.toLowerCase();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#search').focus();$('#search').select();return}if(e.key==='/'&&!['input','textarea','select'].includes(tag)){e.preventDefault();$('#search').focus();return}if(e.key==='Escape'&&document.activeElement===$('#search')&&$('#search').value){e.preventDefault();$('#search').value='';state.page=1;load()}});
injectAccessibilityStyle();
const params=new URLSearchParams(location.search);$('#search').value=params.get('q')||'';$('#platform').value=params.get('platform')||'';$('#position').value=params.get('position')||'';$('#minGames').value=params.get('minGames')||'';$('#minRating').value=params.get('minRating')||'';$('#minGoals').value=params.get('minGoals')||'';$('#minAssists').value=params.get('minAssists')||'';$('#clubFilter').value=params.get('club')||'';$('#activeDays').value=params.get('activeDays')||'0';state.sort=params.get('sort')||'games';state.dir=params.get('dir')==='asc'?'asc':'desc';state.limit=[25,50,100].includes(Number(params.get('limit')))?Number(params.get('limit')):50;$('#pageSize').value=String(state.limit);state.page=Math.max(1,Number(params.get('page')||1));load();