import{$,esc,nf,f2,labels,initials,playerUrl,get}from'./v8-common.js';
const state={page:1,pages:1,total:0,limit:50,timer:null,sort:'games',dir:'desc'};
const textSorts=new Set(['name','club','position']);
function rawRating(p){if(+p.rating>0)return+p.rating;try{const r=JSON.parse(p.raw_json||'{}'),v=Number(r.ratingAve??r.rating??0);return v>10&&v<=100?v/10:v}catch{return 0}}
function pos(p){return p.position||p.recent_role||'—'}
function arrow(key){if(state.sort!==key)return'↕';return state.dir==='desc'?'↓':'↑'}
function sortButton(label,key){const active=state.sort===key?' active':'';return`<button class="sortBtn${active}" data-sort="${key}" aria-label="Trier par ${esc(label)}">${esc(label)} <span>${arrow(key)}</span></button>`}
function renderHead(){const h=$('#head');h.innerHTML=`<div class="rank">#</div><div class="identity">${sortButton('Joueur','name')}</div><div>${sortButton('Club','club')}</div><div>${sortButton('Poste','position')}</div><div class="num">${sortButton('Note','rating')}</div><div class="num">${sortButton('Matchs','games')}</div><div class="num">${sortButton('Buts','goals')}</div><div class="num">${sortButton('Passes','assists')}</div><div class="num">${sortButton('B+P','contributions')}</div>`;h.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const k=b.dataset.sort;if(state.sort===k)state.dir=state.dir==='desc'?'asc':'desc';else{state.sort=k;state.dir=textSorts.has(k)?'asc':'desc'}state.page=1;load()})}
function setUrl(){const u=new URL(location.href),q=$('#search').value.trim(),p=$('#platform').value;if(q)u.searchParams.set('q',q);else u.searchParams.delete('q');if(p)u.searchParams.set('platform',p);else u.searchParams.delete('platform');if(state.sort!=='games'||state.dir!=='desc'){u.searchParams.set('sort',state.sort);u.searchParams.set('dir',state.dir)}else{u.searchParams.delete('sort');u.searchParams.delete('dir')}if(state.page>1)u.searchParams.set('page',state.page);else u.searchParams.delete('page');history.replaceState(null,'',u)}
function playerRow(p,i){const r=rawRating(p),ga=Number(p.goals||0)+Number(p.assists||0),idx=(state.page-1)*state.limit+i+1;return`<div class="row" data-url="${playerUrl(p)}"><div class="rank">${nf(idx)}</div><div class="identity"><div class="avatar">${esc(initials(p.name))}</div><div class="who"><b>${esc(p.name)}</b><span>${esc(labels[p.platform]||p.platform||'')}</span></div></div><div class="club"><b>${esc(p.club_name||'Club inconnu')}</b><span>${p.club_id?`ID ${esc(p.club_id)}`:'—'}</span></div><div><span class="pos">${esc(pos(p))}</span></div><div class="num rating">${f2(r)}</div><div class="num">${nf(p.games)}</div><div class="num">${nf(p.goals)}</div><div class="num">${nf(p.assists)}</div><div class="num ga">${nf(ga)}</div></div>`}
function renderPages(){const box=$('#pages');box.innerHTML='';if(state.pages<=1){$('#prev').disabled=true;$('#next').disabled=true;return}const start=Math.max(1,state.page-2),end=Math.min(state.pages,start+4);for(let p=start;p<=end;p++){const b=document.createElement('button');b.className='pagebtn'+(p===state.page?' active':'');b.textContent=p;b.onclick=()=>{state.page=p;load();scrollTo({top:0,behavior:'smooth'})};box.appendChild(b)}$('#prev').disabled=state.page<=1;$('#next').disabled=state.page>=state.pages}
async function load(){setUrl();renderHead();$('#rows').innerHTML='<div class="empty">Chargement des joueurs…</div>';$('#empty').hidden=true;try{const q=$('#search').value.trim(),platform=$('#platform').value,sort=`${state.sort}:${state.dir}`,r=await get(`/api/players?q=${encodeURIComponent(q)}&platform=${encodeURIComponent(platform)}&sort=${encodeURIComponent(sort)}&page=${state.page}&limit=${state.limit}`);state.total=r.total||0;state.pages=r.pages||1;$('#playerCount').textContent=nf(state.total);$('#resultText').textContent=q?`${nf(state.total)} résultat${state.total>1?'s':''} pour « ${q} »`:`${nf(state.total)} joueurs dans la base`;$('#rows').innerHTML=(r.items||[]).map(playerRow).join('');$('#empty').hidden=(r.items||[]).length>0;renderPages();document.querySelectorAll('[data-url]').forEach(x=>x.onclick=()=>location.href=x.dataset.url)}catch(e){$('#rows').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
$('#search').oninput=()=>{clearTimeout(state.timer);state.timer=setTimeout(()=>{state.page=1;load()},220)};$('#platform').onchange=()=>{state.page=1;load()};$('#prev').onclick=()=>{if(state.page>1){state.page--;load()}};$('#next').onclick=()=>{if(state.page<state.pages){state.page++;load()}};
const params=new URLSearchParams(location.search);$('#search').value=params.get('q')||'';$('#platform').value=params.get('platform')||'';state.sort=params.get('sort')||'games';state.dir=params.get('dir')==='asc'?'asc':'desc';state.page=Math.max(1,Number(params.get('page')||1));load();