import{$,esc,nf,f2,labels,playerUrl,clubUrl,get}from'./v8-common.js';
const state={page:1,pages:1,limit:50,sort:'goals',dir:'desc'};const textSorts=new Set(['name','club','platform','position']);
function arrow(key){if(state.sort!==key)return'↕';return state.dir==='desc'?'↓':'↑'}
function sb(label,key){const active=state.sort===key?' active':'';return`<button class="sortBtn${active}" data-sort="${key}">${esc(label)} <span>${arrow(key)}</span></button>`}
function setUrl(){const u=new URL(location.href),type=$('#type').value,platform=$('#platform').value,min=$('#minGames').value;if(type!=='player')u.searchParams.set('type',type);else u.searchParams.delete('type');if(platform)u.searchParams.set('platform',platform);else u.searchParams.delete('platform');if(min!=='3')u.searchParams.set('minGames',min);else u.searchParams.delete('minGames');const def=type==='club'?'skill':'goals';if(state.sort!==def||state.dir!=='desc'){u.searchParams.set('metric',state.sort);u.searchParams.set('dir',state.dir)}else{u.searchParams.delete('metric');u.searchParams.delete('dir')}if(state.page>1)u.searchParams.set('page',state.page);else u.searchParams.delete('page');history.replaceState(null,'',u)}
function bindSort(){document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const k=b.dataset.sort;if(state.sort===k)state.dir=state.dir==='desc'?'asc':'desc';else{state.sort=k;state.dir=textSorts.has(k)?'asc':'desc'}state.page=1;load()})}
function playerHead(){const h=$('#head');h.style.gridTemplateColumns='60px 1.5fr 1.2fr 115px 95px 80px 78px 70px 70px 78px 72px 72px';h.innerHTML=`<div>#</div><div>${sb('Joueur','name')}</div><div>${sb('Club','club')}</div><div>${sb('Plateforme','platform')}</div><div>${sb('Poste','position')}</div><div class="num">${sb('Note','rating')}</div><div class="num">${sb('Matchs','games')}</div><div class="num">${sb('Buts','goals')}</div><div class="num">${sb('Passes','assists')}</div><div class="num">${sb('B+P','contributions')}</div><div class="num">${sb('B/M','gpg')}</div><div class="num">${sb('P/M','apg')}</div>`}
function clubHead(){const h=$('#head');h.style.gridTemplateColumns='60px 1.8fr 130px 100px 88px 70px 70px 70px 88px';h.innerHTML=`<div>#</div><div>${sb('Club','name')}</div><div>${sb('Plateforme','platform')}</div><div class="num">${sb('Skill','skill')}</div><div class="num">${sb('Matchs','games')}</div><div class="num">${sb('V','wins')}</div><div class="num">${sb('N','draws')}</div><div class="num">${sb('D','losses')}</div><div class="num">${sb('% V','winrate')}</div>`}
function playerRow(x,i){const gp=Number(x.games||0),bp=Number(x.goals||0)+Number(x.assists||0),gpg=gp?Number(x.goals||0)/gp:0,apg=gp?Number(x.assists||0)/gp:0;return`<a class="row" style="grid-template-columns:60px 1.5fr 1.2fr 115px 95px 80px 78px 70px 70px 78px 72px 72px" href="${playerUrl(x)}"><div>#${nf((state.page-1)*state.limit+i+1)}</div><div class="identity"><div class="avatar">${esc(x.name?.[0]||'?')}</div><div><b>${esc(x.name)}</b></div></div><div>${esc(x.club_name||'Sans club')}</div><div>${esc(labels[x.platform]||x.platform)}</div><div>${esc(x.position||'—')}</div><div class="num rating">${f2(x.rating)}</div><div class="num">${nf(x.games)}</div><div class="num good">${nf(x.goals)}</div><div class="num">${nf(x.assists)}</div><div class="num rating">${nf(bp)}</div><div class="num">${gpg.toFixed(2)}</div><div class="num">${apg.toFixed(2)}</div></a>`}
function clubRow(x,i){const wr=Number(x.games||0)?Number(x.wins||0)/Number(x.games)*100:0;return`<a class="row" style="grid-template-columns:60px 1.8fr 130px 100px 88px 70px 70px 70px 88px" href="${clubUrl(x)}"><div>#${nf((state.page-1)*state.limit+i+1)}</div><div class="identity"><div class="crest">${esc(x.name?.[0]||'?')}</div><div><b>${esc(x.name)}</b></div></div><div>${esc(labels[x.platform]||x.platform)}</div><div class="num rating">${nf(x.skill)}</div><div class="num">${nf(x.games)}</div><div class="num good">${nf(x.wins)}</div><div class="num warn">${nf(x.draws)}</div><div class="num bad">${nf(x.losses)}</div><div class="num good">${wr.toFixed(1)}%</div></a>`}
function renderPages(){const b=$('#pages');b.innerHTML='';const start=Math.max(1,state.page-2),end=Math.min(state.pages,start+4);for(let p=start;p<=end;p++){const x=document.createElement('button');x.textContent=p;x.className=p===state.page?'active':'';x.onclick=()=>{state.page=p;load();scrollTo({top:0,behavior:'smooth'})};b.appendChild(x)}$('#prev').disabled=state.page<=1;$('#next').disabled=state.page>=state.pages}
async function load(){setUrl();const type=$('#type').value,platform=$('#platform').value,min=$('#minGames').value;if(type==='club')clubHead();else playerHead();bindSort();$('#rows').innerHTML='<div class="empty">Chargement…</div>';try{const r=await get(`/api/v8/rankings?type=${type}&metric=${encodeURIComponent(`${state.sort}:${state.dir}`)}&platform=${encodeURIComponent(platform)}&minGames=${min}&page=${state.page}&limit=${state.limit}`);state.pages=r.pages||1;$('#summary').textContent=`${nf(r.total)} ${type==='club'?'clubs':'joueurs'} classés • tri ${state.dir==='desc'?'décroissant':'croissant'}`;$('#rows').innerHTML=(r.items||[]).map((x,i)=>type==='club'?clubRow(x,i):playerRow(x,i)).join('')||'<div class="empty">Aucune donnée.</div>';renderPages()}catch(e){$('#rows').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
const p=new URLSearchParams(location.search);$('#type').value=p.get('type')||'player';$('#platform').value=p.get('platform')||'';$('#minGames').value=p.get('minGames')||'3';state.sort=p.get('metric')||($('#type').value==='club'?'skill':'goals');state.dir=p.get('dir')==='asc'?'asc':'desc';state.page=Math.max(1,Number(p.get('page')||1));$('#type').onchange=()=>{state.sort=$('#type').value==='club'?'skill':'goals';state.dir='desc';state.page=1;load()};for(const id of['platform','minGames'])$('#'+id).onchange=()=>{state.page=1;load()};$('#prev').onclick=()=>{if(state.page>1){state.page--;load()}};$('#next').onclick=()=>{if(state.page<state.pages){state.page++;load()}};load();