export const $=s=>document.querySelector(s);
export const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
export const nf=n=>new Intl.NumberFormat('fr-FR').format(Number(n||0));
export const f1=n=>Number(n||0)>0?Number(n).toFixed(1):'—';
export const f2=n=>Number(n||0)>0?Number(n).toFixed(2):'—';
export const labels={"common-gen5":"Current Gen","common-gen4":"Last Gen",nx:"Switch"};
export const slug=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'profil';
export const playerUrl=p=>`/fr/player/${encodeURIComponent(p.platform)}/${encodeURIComponent(p.player_id)}/${slug(p.name)}`;
export const clubUrl=c=>`/fr/club/${encodeURIComponent(c.platform)}/${encodeURIComponent(c.club_id)}/${slug(c.name)}`;
export const matchUrl=m=>`/fr/match/${encodeURIComponent(m.platform)}/${encodeURIComponent(m.match_id)}`;
export const initials=n=>String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase().slice(0,2)||'?';
export async function get(url,opts){const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erreur serveur');return d}
export function relative(ts){const s=Math.max(0,Math.floor(Date.now()/1000)-Number(ts||0));if(!ts)return'—';if(s<60)return'il y a moins d’une minute';if(s<3600)return`il y a ${Math.floor(s/60)} min`;if(s<86400)return`il y a ${Math.floor(s/3600)} h`;return`il y a ${Math.floor(s/86400)} j`}
export function dateTime(ts){return ts?new Date(Number(ts)*1000).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}
export function sparkline(values=[]){const a=values.map(Number).filter(Number.isFinite);if(!a.length)return'<div class="empty">Pas assez de données pour la courbe.</div>';const w=520,h=150,p=12,min=Math.min(...a),max=Math.max(...a),span=Math.max(.01,max-min),pts=a.map((v,i)=>`${p+(w-p*2)*(a.length===1?.5:i/(a.length-1))},${h-p-(h-p*2)*(v-min)/span}`).join(' ');return`<div class="spark"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Courbe de forme"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" class="sparkAxis"/><polyline points="${pts}" class="sparkLine"/>${pts.split(' ').map((xy,i)=>{const[x,y]=xy.split(',');return`<circle cx="${x}" cy="${y}" r="4" class="sparkDot"><title>${a[i].toFixed(2)}</title></circle>`}).join('')}</svg><div class="sparkScale"><span>${min.toFixed(2)}</span><span>${max.toFixed(2)}</span></div></div>`}
const HISTORY_KEY='fcg_search_history_v8',FAV_KEY='fcg_favorites_v9';
function history(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}}
function remember(item){try{const old=history().filter(x=>x.url!==item.url),next=[item,...old].slice(0,8);localStorage.setItem(HISTORY_KEY,JSON.stringify(next))}catch{}}
function historyHtml(){const h=history();if(!h.length)return'';return`<div class="searchHistoryTitle">Recherches récentes</div>${h.map(x=>`<a class="suggestion recent" href="${esc(x.url)}"><div class="${x.type==='Joueur'?'avatar':'crest'}">${esc(initials(x.name))}</div><div><b>${esc(x.name)}</b><div class="small muted">${esc(x.subtitle||x.type)}</div></div><span class="badge">${esc(x.type)}</span></a>`).join('')}`}
export function getFavorites(){try{return JSON.parse(localStorage.getItem(FAV_KEY)||'[]')}catch{return[]}}
export function isFavorite(type,platform,id){return getFavorites().some(x=>x.type===type&&x.platform===platform&&String(x.id)===String(id))}
export function toggleFavorite(item){const all=getFavorites(),i=all.findIndex(x=>x.type===item.type&&x.platform===item.platform&&String(x.id)===String(item.id));let active;if(i>=0){all.splice(i,1);active=false}else{all.unshift({...item,addedAt:Date.now()});active=true}try{localStorage.setItem(FAV_KEY,JSON.stringify(all.slice(0,100)))}catch{}return active}
export function favoriteButton(type,obj){const id=type==='player'?obj.player_id:obj.club_id,active=isFavorite(type,obj.platform,id);return`<button class="btn secondary favBtn" data-fav-type="${type}" data-fav-platform="${esc(obj.platform)}" data-fav-id="${esc(id)}" data-fav-name="${esc(obj.name)}" data-fav-club="${esc(obj.club_name||'')}">${active?'★ Favori':'☆ Ajouter aux favoris'}</button>`}
export function bindFavoriteButtons(root=document){root.querySelectorAll('.favBtn').forEach(b=>b.onclick=()=>{const active=toggleFavorite({type:b.dataset.favType,platform:b.dataset.favPlatform,id:b.dataset.favId,name:b.dataset.favName,club_name:b.dataset.favClub});b.textContent=active?'★ Favori':'☆ Ajouter aux favoris'})}
export function attachGlobalSearch(input,box){if(!input||!box)return;let timer;const bind=()=>box.querySelectorAll('a.suggestion').forEach(a=>a.addEventListener('click',()=>remember({name:a.querySelector('b')?.textContent||'',subtitle:a.querySelector('.small')?.textContent||'',type:a.querySelector('.badge')?.textContent||'',url:a.getAttribute('href')||'/'})));const showHistory=()=>{if(input.value.trim())return;const h=historyHtml();if(h){box.innerHTML=h;box.hidden=false;bind()}};input.addEventListener('focus',showHistory);input.addEventListener('input',()=>{clearTimeout(timer);const q=input.value.trim();if(q.length<2){box.innerHTML='';box.hidden=true;if(!q)showHistory();return}timer=setTimeout(async()=>{try{const r=await get(`/api/v8/search?q=${encodeURIComponent(q)}&limit=6`),items=[];for(const p of r.players||[])items.push(`<a class="suggestion" href="${playerUrl(p)}"><div class="avatar">${esc(initials(p.name))}</div><div><b>${esc(p.name)}</b><div class="small muted">Joueur • ${esc(p.club_name||'Sans club')} • ${esc(labels[p.platform]||p.platform)}</div></div><span class="badge">Joueur</span></a>`);for(const c of r.clubs||[])items.push(`<a class="suggestion" href="${clubUrl(c)}"><div class="crest">${esc(initials(c.name))}</div><div><b>${esc(c.name)}</b><div class="small muted">Club • ${esc(labels[c.platform]||c.platform)} • ${nf(c.games)} matchs</div></div><span class="badge">Club</span></a>`);box.innerHTML=items.join('')||'<div class="empty">Aucun résultat</div>';box.hidden=false;bind()}catch{box.hidden=true}},180)});document.addEventListener('click',e=>{if(e.target!==input&&!box.contains(e.target))box.hidden=true})}
function enhanceNav(){const top=document.querySelector('.topinner'),nav=top?.querySelector('nav');if(!top||!nav)return;const links=[['/fr/records','Records'],['/fr/h2h','Face-à-face'],['/fr/live','Live'],['/fr/favorites','Favoris']];for(const[href,text]of links)if(![...nav.querySelectorAll('a')].some(a=>a.getAttribute('href')===href)){const a=document.createElement('a');a.href=href;a.textContent=text;nav.appendChild(a)}if(!top.querySelector('.seasonSwitch')){const s=document.createElement('select');s.className='seasonSwitch';s.innerHTML='<option value="fc26">FC 26</option><option value="fc27" disabled>FC 27 — bientôt</option>';s.title='Saison';top.appendChild(s)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhanceNav);else enhanceNav();
