export const $=s=>document.querySelector(s);
export const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
export const nf=n=>new Intl.NumberFormat('fr-FR').format(Number(n||0));
export const f1=n=>Number(n||0)>0?Number(n).toFixed(1):'—';
export const f2=n=>Number(n||0)>0?Number(n).toFixed(2):'—';
export const labels={"common-gen5":"Current Gen","common-gen4":"Last Gen",nx:"Switch"};
export const slug=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70)||'profil';
export const playerUrl=p=>`/fr/player/${encodeURIComponent(p.platform)}/${encodeURIComponent(p.player_id)}/${slug(p.name)}`;
export const clubUrl=c=>`/fr/club/${encodeURIComponent(c.platform)}/${encodeURIComponent(c.club_id)}/${slug(c.name)}`;
export const matchUrl=m=>`/fr/match/${encodeURIComponent(m.platform)}/${encodeURIComponent(m.match_id)}`;
export const initials=n=>String(n||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase().slice(0,2)||'?';
export async function get(url,opts){const r=await fetch(url,opts);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Erreur serveur');return d}
export function relative(ts){const s=Math.max(0,Math.floor(Date.now()/1000)-Number(ts||0));if(!ts)return'—';if(s<60)return'il y a moins d’une minute';if(s<3600)return`il y a ${Math.floor(s/60)} min`;if(s<86400)return`il y a ${Math.floor(s/3600)} h`;return`il y a ${Math.floor(s/86400)} j`}
export function dateTime(ts){return ts?new Date(Number(ts)*1000).toLocaleString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'}
export function sparkline(values=[]){const a=values.map(Number).filter(Number.isFinite);if(!a.length)return'<div class="empty">Pas assez de données pour la courbe.</div>';const w=520,h=150,p=12,min=Math.min(...a),max=Math.max(...a),span=Math.max(.01,max-min),points=a.map((v,i)=>({v,x:p+(w-p*2)*(a.length===1?.5:i/(a.length-1)),y:h-p-(h-p*2)*(v-min)/span})),pts=points.map(o=>`${o.x},${o.y}`).join(' ');return`<div class="spark"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Courbe de forme"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}" class="sparkAxis"/><polyline points="${pts}" class="sparkLine"/>${points.map(o=>{const tx=Math.max(52,Math.min(w-52,o.x)),below=o.y<42,ry=below?o.y+10:o.y-36;return`<g class="sparkPoint" tabindex="0"><circle cx="${o.x}" cy="${o.y}" r="5" class="sparkDot"/><g class="sparkTip"><rect x="${tx-46}" y="${ry}" width="92" height="25" rx="8"/><text x="${tx}" y="${ry+17}" text-anchor="middle">${o.v.toFixed(2)}</text></g></g>`}).join('')}</svg><div class="sparkScale"><span>${min.toFixed(2)}</span><span>Survole un point pour voir la valeur</span><span>${max.toFixed(2)}</span></div></div>`}
const HISTORY_KEY='fcg_search_history_v8',FAV_KEY='fcg_favorites_v9';
function history(){try{return JSON.parse(localStorage.getItem(HISTORY_KEY)||'[]')}catch{return[]}}
function remember(item){try{const old=history().filter(x=>x.url!==item.url),next=[item,...old].slice(0,8);localStorage.setItem(HISTORY_KEY,JSON.stringify(next))}catch{}}
function historyHtml(){const h=history();if(!h.length)return'';return`<div class="searchHistoryTitle">Recherches récentes</div>${h.map(x=>`<a class="suggestion recent" href="${esc(x.url)}"><div class="${x.type==='Joueur'?'avatar':'crest'}">${esc(initials(x.name))}</div><div><b>${esc(x.name)}</b><div class="small muted">${esc(x.subtitle||x.type)}</div></div><span class="badge">${esc(x.type)}</span></a>`).join('')}`}
export function getFavorites(){try{return JSON.parse(localStorage.getItem(FAV_KEY)||'[]')}catch{return[]}}
export function isFavorite(type,platform,id){return getFavorites().some(x=>x.type===type&&x.platform===platform&&String(x.id)===String(id))}
export function toggleFavorite(item){const all=getFavorites(),i=all.findIndex(x=>x.type===item.type&&x.platform===item.platform&&String(x.id)===String(item.id));let active;if(i>=0){all.splice(i,1);active=false}else{all.unshift({...item,addedAt:Date.now()});active=true}try{localStorage.setItem(FAV_KEY,JSON.stringify(all.slice(0,100)))}catch{}return active}
export function favoriteButton(type,obj){const id=type==='player'?obj.player_id:obj.club_id,active=isFavorite(type,obj.platform,id);return`<button class="btn secondary favBtn" data-fav-type="${type}" data-fav-platform="${esc(obj.platform)}" data-fav-id="${esc(id)}" data-fav-name="${esc(obj.name)}" data-fav-club="${esc(obj.club_name||'')}">${active?'★ Favori':'☆ Ajouter aux favoris'}</button>`}
export function bindFavoriteButtons(root=document){root.querySelectorAll('.favBtn').forEach(b=>b.onclick=()=>{const active=toggleFavorite({type:b.dataset.favType,platform:b.dataset.favPlatform,id:b.dataset.favId,name:b.dataset.favName,club_name:b.dataset.favClub});b.textContent=active?'★ Favori':'☆ Ajouter aux favoris'})}
export function attachGlobalSearch(input,box){if(!input||!box)return;let timer;const bind=()=>box.querySelectorAll('a.suggestion').forEach(a=>a.addEventListener('click',()=>remember({name:a.querySelector('b')?.textContent||'',subtitle:a.querySelector('.small')?.textContent||'',type:a.querySelector('.badge')?.textContent||'',url:a.getAttribute('href')||'/'})));const showHistory=()=>{if(input.value.trim())return;const h=historyHtml();if(h){box.innerHTML=h;box.hidden=false;bind()}};input.addEventListener('focus',showHistory);input.addEventListener('input',()=>{clearTimeout(timer);const q=input.value.trim();if(q.length<2){box.innerHTML='';box.hidden=true;if(!q)showHistory();return}timer=setTimeout(async()=>{try{const r=await get(`/api/v8/search?q=${encodeURIComponent(q)}&limit=6`),items=[];for(const p of r.players||[])items.push(`<a class="suggestion" href="${playerUrl(p)}"><div class="avatar">${esc(initials(p.name))}</div><div><b>${esc(p.name)}</b><div class="small muted">Joueur • ${esc(p.club_name||'Sans club')} • ${esc(labels[p.platform]||p.platform)}</div></div><span class="badge">Joueur</span></a>`);for(const c of r.clubs||[])items.push(`<a class="suggestion" href="${clubUrl(c)}"><div class="crest">${esc(initials(c.name))}</div><div><b>${esc(c.name)}</b><div class="small muted">Club • ${esc(labels[c.platform]||c.platform)} • ${nf(c.games)} matchs</div></div><span class="badge">Club</span></a>`);box.innerHTML=items.join('')||'<div class="empty">Aucun résultat</div>';box.hidden=false;bind()}catch{box.hidden=true}},180)});document.addEventListener('click',e=>{if(e.target!==input&&!box.contains(e.target))box.hidden=true})}
function injectVisualPolish(){if(document.getElementById('fcg-v91-visual'))return;const style=document.createElement('style');style.id='fcg-v91-visual';style.textContent=`
html{color-scheme:dark}body{overflow-x:hidden;background:radial-gradient(circle at 8% -8%,#431474 0,transparent 28%),radial-gradient(circle at 92% 4%,#29205f55 0,transparent 26%),linear-gradient(180deg,#090510 0,#0b0711 44%,#08050d 100%)!important;background-attachment:fixed!important}
.topbar{background:linear-gradient(180deg,#0c0714f5,#09060ff0)!important;border-bottom:1px solid #51316b!important;box-shadow:0 12px 38px #0008,0 1px 0 #9b5cf622!important}.topinner{justify-content:flex-start!important;gap:10px!important;min-width:0!important}.logo{flex:0 0 auto!important;text-shadow:0 0 24px #8b5cf644}.logo span{color:#d8c2ff!important;text-shadow:0 0 20px #a855f766}.topinner nav{display:flex!important;align-items:center!important;gap:3px!important;flex:1 1 auto!important;min-width:0!important;overflow:visible!important;scrollbar-width:none!important}.topinner nav::-webkit-scrollbar{display:none!important}.topinner nav a{flex:0 0 auto!important;padding:9px 8px!important;border-radius:10px!important;font-size:13px!important;font-weight:700!important;color:#b9acc4!important;transition:.18s ease!important}.topinner nav a:hover{color:#fff!important;background:#251532!important;box-shadow:inset 0 0 0 1px #6e3f8f!important}.topinner nav a.active{color:#fff!important;background:linear-gradient(135deg,#6d28d9,#9333ea)!important;box-shadow:0 8px 22px #6d28d944,inset 0 0 0 1px #d8b4fe33!important}.seasonSwitch{box-sizing:border-box!important;margin-left:auto!important;width:86px!important;max-width:86px!important;min-width:86px!important;flex:0 0 86px!important;height:38px!important;padding:0 24px 0 10px!important;border-radius:10px!important;border:1px solid #68468a!important;background:#170d22!important;color:#f2eaff!important;font-size:12px!important;font-weight:900!important;box-shadow:0 0 0 1px #8b5cf611 inset!important}
.heroBox,.panel,.card,.stat,.tablewrap,.searchbox,.recordCard,.compareCard,.profileHero,.matchHero,.h2hHero{border-color:#4b3260!important;box-shadow:0 18px 48px #0004,inset 0 1px 0 #ffffff08!important}.heroBox,.profileHero,.matchHero{background:linear-gradient(135deg,#2c1243 0,#151020 48%,#0f0b16 100%)!important}.panel,.card,.stat,.recordCard,.compareCard{background:linear-gradient(180deg,#17101f 0,#100b17 100%)!important}.metric{background:linear-gradient(180deg,#1d1328,#130d1b)!important;border-color:#3d2a4f!important;transition:.18s ease!important}.metric:hover,.card:hover,.recordCard:hover{transform:translateY(-2px);border-color:#7c4fa1!important;box-shadow:0 14px 36px #0006,0 0 22px #7c3aed18!important}.stat b,.metric b,.recordCard strong,.motmRating{color:#eadcff!important;text-shadow:0 0 18px #a855f733}.kicker{color:#c7a8ff!important}.btn,.toolbar button{background:linear-gradient(135deg,#7c3aed,#a855f7)!important;box-shadow:0 8px 22px #7c3aed35!important;transition:.18s ease!important}.btn:hover,.toolbar button:hover{transform:translateY(-1px);filter:brightness(1.12)}.btn.secondary{background:linear-gradient(180deg,#24162f,#1a1123)!important;border-color:#5c3a73!important;box-shadow:none!important}.line,.matchrow,.matchPlayer,.feedItem,.favRow{transition:.15s ease}.line:hover,.matchrow:hover,.matchPlayer:hover,.feedItem:hover,.favRow:hover{background:#23142eaa!important}.badge,.chip{background:#2d1840!important;border-color:#604078!important;color:#eadcff!important}.avatar,.crest{box-shadow:0 0 20px #8b5cf622!important}.globalSearch input,.searchinput input,input,select{border-color:#49305c!important;background:#120b19!important}.globalSearch input:focus,.searchinput input:focus,input:focus,select:focus{border-color:#9d63c9!important;box-shadow:0 0 0 3px #9333ea25,0 0 25px #8b5cf619!important}.tbody .row:hover,.row:hover{background:#21132baa!important}.pagination button,.pagebtn{transition:.16s ease}.pagination button:hover,.pagebtn:hover{border-color:#8154a1!important;background:#24142e!important}
.filterControl{display:grid!important;gap:5px!important;align-self:end!important}.filterControl>span{font-size:10px!important;line-height:1!important;text-transform:uppercase!important;letter-spacing:.09em!important;color:#ab91bf!important;font-weight:900!important;padding-left:3px!important}.filterControl select{margin:0!important}.sortControl select{border-color:#704891!important;background:linear-gradient(180deg,#1b1025,#120b19)!important}.searchrow{align-items:end!important}
.spark{position:relative}.spark svg{overflow:visible!important;background:linear-gradient(180deg,#1b1026,#100a17)!important;border:1px solid #3a274a!important}.sparkLine{stroke:#b56cff!important;filter:drop-shadow(0 0 6px #9333ea88)}.sparkDot{fill:#140b1d!important;stroke:#f0dcff!important;stroke-width:2.4!important;cursor:pointer!important;transition:.15s ease}.sparkPoint:hover .sparkDot,.sparkPoint:focus .sparkDot{r:7;fill:#a855f7!important;stroke:#fff!important}.sparkTip{opacity:0;pointer-events:none;transition:.14s ease}.sparkPoint:hover .sparkTip,.sparkPoint:focus .sparkTip{opacity:1}.sparkTip rect{fill:#09050f;stroke:#b56cff;stroke-width:1.4;filter:drop-shadow(0 6px 10px #0008)}.sparkTip text{fill:#fff;font-size:12px;font-weight:900;font-family:Inter,system-ui,sans-serif}.sparkScale{align-items:center!important;gap:8px!important}.sparkScale span:nth-child(2){color:#bca9ca!important;text-align:center;flex:1}
@media(max-width:1120px){.topinner{flex-wrap:wrap!important;padding:8px 0!important}.topinner nav{order:3!important;width:100%!important;flex-basis:100%!important;flex-wrap:wrap!important}.topinner nav a{font-size:12px!important;padding:7px 8px!important}.seasonSwitch{margin-left:auto!important}}
@media(max-width:650px){.topinner{flex-direction:row!important;align-items:center!important}.topinner nav{order:3!important;display:flex!important;flex-wrap:wrap!important;width:100%!important;gap:4px!important}.topinner nav a{padding:7px 8px!important;font-size:11px!important}.seasonSwitch{width:78px!important;min-width:78px!important;max-width:78px!important;flex-basis:78px!important;height:34px!important}.filterControl>span{font-size:9px!important}}
`;document.head.appendChild(style)}
function enhanceSortControls(){const row=document.querySelector('.searchrow');if(!row)return;const wrap=(el,label,cls)=>{if(!el||el.parentElement?.classList.contains('filterControl'))return;const holder=document.createElement('label');holder.className=`filterControl ${cls}`;const cap=document.createElement('span');cap.textContent=label;el.parentNode.insertBefore(holder,el);holder.append(cap,el)};wrap(row.querySelector('#platform'),'Plateforme','platformControl');wrap(row.querySelector('#sort'),'Trier par','sortControl')}
function enhanceNav(){const top=document.querySelector('.topinner'),nav=top?.querySelector('nav');if(!top||!nav)return;const links=[['/fr/records','Records'],['/fr/h2h','Face-à-face'],['/fr/live','Live'],['/fr/favorites','Favoris']];for(const[href,text]of links)if(![...nav.querySelectorAll('a')].some(a=>a.getAttribute('href')===href)){const a=document.createElement('a');a.href=href;a.textContent=text;nav.appendChild(a)}if(!top.querySelector('.seasonSwitch')){const s=document.createElement('select');s.className='seasonSwitch';s.innerHTML='<option value="fc26">FC 26</option><option value="fc27" disabled>FC 27 — bientôt</option>';s.title='Saison';s.setAttribute('aria-label','Saison');top.appendChild(s)}}
function enhanceUI(){injectVisualPolish();enhanceNav();enhanceSortControls()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhanceUI);else enhanceUI();
