import http from 'node:http';
import { DatabaseSync } from 'node:sqlite';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR=path.dirname(fileURLToPath(import.meta.url));
const HOST=process.env.HOST||'0.0.0.0';
const PORT=Number(process.env.PORT||3000);
const DATA_DIR=process.env.DATA_DIR||'/tmp/fc-clubs-v2';
const BASE='https://proclubs.ea.com/api/fc';
const PLATFORMS=['common-gen5','common-gen4','nx'];
const LABEL={'common-gen5':'Current Gen','common-gen4':'Last Gen',nx:'Switch'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const norm=s=>String(s??'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');
const uid=(p,id)=>`FC26:${p}:${id}`;

fs.mkdirSync(DATA_DIR,{recursive:true});
const db=new DatabaseSync(path.join(DATA_DIR,'fcclubs.db'));
db.exec(`PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS clubs(uid TEXT PRIMARY KEY,platform TEXT,club_id TEXT,name TEXT,name_norm TEXT DEFAULT '',skill REAL DEFAULT 0,wins INTEGER DEFAULT 0,draws INTEGER DEFAULT 0,losses INTEGER DEFAULT 0,games INTEGER DEFAULT 0,updated_at INTEGER DEFAULT 0,synced_at INTEGER DEFAULT 0,raw_json TEXT);
CREATE TABLE IF NOT EXISTS players(uid TEXT PRIMARY KEY,platform TEXT,player_id TEXT,name TEXT,name_norm TEXT DEFAULT '',club_id TEXT,club_name TEXT,games INTEGER DEFAULT 0,goals INTEGER DEFAULT 0,assists INTEGER DEFAULT 0,rating REAL DEFAULT 0,updated_at INTEGER DEFAULT 0,raw_json TEXT);
CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT);
CREATE INDEX IF NOT EXISTS clubs_name ON clubs(name_norm);CREATE INDEX IF NOT EXISTS clubs_platform ON clubs(platform);CREATE INDEX IF NOT EXISTS players_name ON players(name_norm);CREATE INDEX IF NOT EXISTS players_club ON players(platform,club_id);`);

const upClub=db.prepare(`INSERT INTO clubs(uid,platform,club_id,name,name_norm,skill,wins,draws,losses,games,updated_at,raw_json) VALUES(?,?,?,?,?,?,?,?,?,?,unixepoch(),?) ON CONFLICT(uid) DO UPDATE SET name=excluded.name,name_norm=excluded.name_norm,skill=CASE WHEN excluded.skill>0 THEN excluded.skill ELSE clubs.skill END,wins=MAX(clubs.wins,excluded.wins),draws=MAX(clubs.draws,excluded.draws),losses=MAX(clubs.losses,excluded.losses),games=MAX(clubs.games,excluded.games),updated_at=unixepoch(),raw_json=excluded.raw_json`);
const upPlayer=db.prepare(`INSERT INTO players(uid,platform,player_id,name,name_norm,club_id,club_name,games,goals,assists,rating,updated_at,raw_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,unixepoch(),?) ON CONFLICT(uid) DO UPDATE SET name=excluded.name,name_norm=excluded.name_norm,club_id=excluded.club_id,club_name=excluded.club_name,games=MAX(players.games,excluded.games),goals=MAX(players.goals,excluded.goals),assists=MAX(players.assists,excluded.assists),rating=CASE WHEN excluded.rating>0 THEN excluded.rating ELSE players.rating END,updated_at=unixepoch(),raw_json=excluded.raw_json`);

function sendJson(res,code,data){res.writeHead(code,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data));}
async function ea(endpoint,params){const u=new URL(BASE+endpoint);for(const[k,v]of Object.entries(params))u.searchParams.set(k,String(v));const r=await fetch(u,{headers:{accept:'application/json','user-agent':'Mozilla/5.0 FC-Clubs-Global'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`EA ${r.status}`);return r.json();}
function extractClubs(payload,p){const out=[],seen=new Set();const walk=(v,d=0)=>{if(d>6||v==null)return;if(Array.isArray(v)){v.forEach(x=>walk(x,d+1));return;}if(typeof v!=='object')return;const id=v.clubId??v.club_id??v.id,name=v.clubName??v.name??v.club?.name;if(id&&name&&!seen.has(String(id))){seen.add(String(id));const x={id:String(id),name:String(name),skill:num(v.skillRating??v.skillrating??v.skill),wins:num(v.wins),draws:num(v.draws??v.ties),losses:num(v.losses),games:num(v.games??v.gamesPlayed),raw:v};out.push(x);upClub.run(uid(p,x.id),p,x.id,x.name,norm(x.name),x.skill,x.wins,x.draws,x.losses,x.games,JSON.stringify(x.raw));}Object.values(v).forEach(x=>{if(x&&typeof x==='object')walk(x,d+1)});};walk(payload);return out;}
function extractPlayers(payload,p,clubId,clubName){const out=[],seen=new Set();const walk=(v,d=0)=>{if(d>6||v==null)return;if(Array.isArray(v)){v.forEach(x=>walk(x,d+1));return;}if(typeof v!=='object')return;const name=v.name??v.playerName??v.proName??v.eaId??v.playername,id=v.playerId??v.player_id??v.personaId??v.blazeId??name;if(name&&id&&!seen.has(String(id))){seen.add(String(id));const x={id:String(id),name:String(name),games:num(v.games??v.gamesPlayed??v.appearances),goals:num(v.goals),assists:num(v.assists),rating:num(v.rating??v.averageRating??v.avgRating)};out.push(x);upPlayer.run(uid(p,x.id),p,x.id,x.name,norm(x.name),clubId,clubName,x.games,x.goals,x.assists,x.rating,JSON.stringify(v));}Object.values(v).forEach(x=>{if(x&&typeof x==='object')walk(x,d+1)});};walk(payload);return out;}

let running=false;let crawl={running:false,scanned:0,clubs:0,players:0,discovered:0,lastError:'',platform:'',prefix:''};
const chars='abcdefghijklmnopqrstuvwxyz0123456789';const prefixes=[...chars,...[...chars].flatMap(a=>[...chars].map(b=>a+b))];
const getMeta=(k,d='0')=>db.prepare('SELECT value FROM meta WHERE key=?').get(k)?.value??d;
const setMeta=(k,v)=>db.prepare('INSERT INTO meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').run(k,String(v));
async function syncClub(row,p){let clubName=row.name||'';try{const info=extractClubs(await ea('/clubs/info',{platform:p,clubIds:row.club_id}),p);clubName=info.find(x=>x.id===row.club_id)?.name||clubName;}catch(e){crawl.lastError=e.message;}for(const ep of ['/members/career/stats','/members/stats']){await sleep(Number(process.env.EA_REQUEST_GAP_MS||650));try{crawl.players+=extractPlayers(await ea(ep,{platform:p,clubId:row.club_id}),p,row.club_id,clubName).length;}catch(e){crawl.lastError=e.message;}}db.prepare('UPDATE clubs SET synced_at=unixepoch() WHERE platform=? AND club_id=?').run(p,row.club_id);}
async function runCrawler(){if(running)return;running=true;crawl={running:true,scanned:0,clubs:0,players:0,discovered:0,lastError:'',platform:'',prefix:''};try{for(const p of PLATFORMS){crawl.platform=p;for(const ep of ['/allTimeLeaderboard','/currentSeasonLeaderboard']){try{crawl.discovered+=extractClubs(await ea(ep,{platform:p,maxResultCount:100}),p).length;}catch(e){crawl.lastError=e.message;}await sleep(Number(process.env.EA_REQUEST_GAP_MS||650));}let cursor=Number(getMeta('cursor:'+p,0))||0;const batch=Math.max(10,Number(process.env.CRAWL_PREFIX_BATCH||35));for(let i=0;i<batch;i++){const prefix=prefixes[cursor%prefixes.length];crawl.prefix=prefix;for(const ep of ['/allTimeLeaderboard/search','/currentSeasonLeaderboard/search']){try{crawl.discovered+=extractClubs(await ea(ep,{platform:p,clubName:prefix,maxResultCount:50}),p).length;}catch(e){crawl.lastError=e.message;}crawl.scanned++;await sleep(Number(process.env.EA_REQUEST_GAP_MS||650));}cursor=(cursor+1)%prefixes.length;setMeta('cursor:'+p,cursor);}const clubs=db.prepare('SELECT club_id,name FROM clubs WHERE platform=? ORDER BY synced_at ASC,updated_at DESC LIMIT ?').all(p,Math.max(15,Number(process.env.CRAWL_SYNC_BATCH||50)));for(const c of clubs){await syncClub(c,p);crawl.clubs++;}}}finally{crawl.running=false;crawl.platform='';crawl.prefix='';running=false;}}

const indexHtml=fs.readFileSync(path.join(DIR,'index.html'),'utf8');
const clubOrder={skill:'skill DESC,games DESC',games:'games DESC,skill DESC',name:'name COLLATE NOCASE ASC',recent:'updated_at DESC'};
const playerOrder={rating:'rating DESC,games DESC',goals:'goals DESC,games DESC',assists:'assists DESC,games DESC',games:'games DESC,goals DESC',name:'name COLLATE NOCASE ASC',recent:'updated_at DESC'};
const page=u=>{const p=Math.max(1,Number(u.searchParams.get('page')||1)),limit=Math.min(60,Math.max(12,Number(u.searchParams.get('limit')||30)));return{p,limit,offset:(p-1)*limit};};
const decorate=x=>({...x,platform_label:LABEL[x.platform]||x.platform});

const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://local');
if(u.pathname==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-cache'});return res.end(indexHtml);}
if(u.pathname==='/api/health')return sendJson(res,200,{ok:true,version:'v2',game:'FC26'});
if(u.pathname==='/api/crawl')return sendJson(res,200,crawl);
if(u.pathname==='/api/dashboard'){const clubs=db.prepare('SELECT COUNT(*) c FROM clubs').get().c,players=db.prepare('SELECT COUNT(*) c FROM players').get().c,games=db.prepare('SELECT COALESCE(SUM(games),0) c FROM clubs').get().c,platforms=db.prepare('SELECT COUNT(DISTINCT platform) c FROM clubs').get().c;return sendJson(res,200,{clubs,players,games,platforms});}
if(u.pathname==='/api/search'){const q=norm(u.searchParams.get('q')),p=u.searchParams.get('platform')||'',pat='%'+q+'%';const clubs=db.prepare("SELECT platform,club_id,name,skill,wins,draws,losses,games FROM clubs WHERE (?='' OR platform=?) AND (?='' OR name_norm LIKE ?) ORDER BY CASE WHEN name_norm=? THEN 0 WHEN name_norm LIKE ? THEN 1 ELSE 2 END,skill DESC LIMIT 20").all(p,p,q,pat,q,q+'%').map(decorate);const players=db.prepare("SELECT platform,player_id,name,club_id,club_name,games,goals,assists,rating FROM players WHERE (?='' OR platform=?) AND (?='' OR name_norm LIKE ?) ORDER BY CASE WHEN name_norm=? THEN 0 WHEN name_norm LIKE ? THEN 1 ELSE 2 END,rating DESC,games DESC LIMIT 20").all(p,p,q,pat,q,q+'%').map(decorate);return sendJson(res,200,{clubs,players});}
if(u.pathname==='/api/clubs'){const q=norm(u.searchParams.get('q')),p=u.searchParams.get('platform')||'',sort=u.searchParams.get('sort')||'skill',pg=page(u),pat='%'+q+'%',where="(?='' OR platform=?) AND (?='' OR name_norm LIKE ?)",total=db.prepare(`SELECT COUNT(*) c FROM clubs WHERE ${where}`).get(p,p,q,pat).c,items=db.prepare(`SELECT platform,club_id,name,skill,wins,draws,losses,games FROM clubs WHERE ${where} ORDER BY ${clubOrder[sort]||clubOrder.skill} LIMIT ? OFFSET ?`).all(p,p,q,pat,pg.limit,pg.offset).map(decorate);return sendJson(res,200,{page:pg.p,total,pages:Math.max(1,Math.ceil(total/pg.limit)),items});}
if(u.pathname==='/api/players'){const q=norm(u.searchParams.get('q')),p=u.searchParams.get('platform')||'',sort=u.searchParams.get('sort')||'rating',pg=page(u),pat='%'+q+'%',where="(?='' OR platform=?) AND (?='' OR name_norm LIKE ?)",total=db.prepare(`SELECT COUNT(*) c FROM players WHERE ${where}`).get(p,p,q,pat).c,items=db.prepare(`SELECT platform,player_id,name,club_id,club_name,games,goals,assists,rating FROM players WHERE ${where} ORDER BY ${playerOrder[sort]||playerOrder.rating} LIMIT ? OFFSET ?`).all(p,p,q,pat,pg.limit,pg.offset).map(decorate);return sendJson(res,200,{page:pg.p,total,pages:Math.max(1,Math.ceil(total/pg.limit)),items});}
if(u.pathname==='/api/rankings'){const p=u.searchParams.get('platform')||'',m=['goals','assists','rating','games'].includes(u.searchParams.get('metric'))?u.searchParams.get('metric'):'goals';const items=db.prepare(`SELECT platform,player_id,name,club_name,games,goals,assists,rating FROM players WHERE (?='' OR platform=?) AND games>0 ORDER BY ${m} DESC,games DESC LIMIT 50`).all(p,p).map(decorate);return sendJson(res,200,{metric:m,items});}
if(u.pathname==='/api/club'){const p=u.searchParams.get('platform')||'',id=u.searchParams.get('id')||'',club=db.prepare('SELECT * FROM clubs WHERE platform=? AND club_id=?').get(p,id);if(!club)return sendJson(res,404,{error:'Club introuvable'});const players=db.prepare('SELECT platform,player_id,name,club_name,games,goals,assists,rating FROM players WHERE platform=? AND club_id=? ORDER BY rating DESC,goals DESC,games DESC LIMIT 100').all(p,id).map(decorate);return sendJson(res,200,{club:decorate(club),players});}
if(u.pathname==='/api/player'){const p=u.searchParams.get('platform')||'',id=u.searchParams.get('id')||'',x=db.prepare('SELECT * FROM players WHERE platform=? AND player_id=?').get(p,id);if(!x)return sendJson(res,404,{error:'Joueur introuvable'});return sendJson(res,200,{player:{...decorate(x),gpg:x.games?x.goals/x.games:0,apg:x.games?x.assists/x.games:0}});}
return sendJson(res,404,{error:'not found'});}catch(e){console.error(e);return sendJson(res,500,{error:e.message});}});
server.listen(PORT,HOST,()=>{console.log(`FC Clubs Global V2 on ${HOST}:${PORT}`);if(process.env.AUTO_MAX_CRAWL!=='0')setTimeout(runCrawler,1000);});
setInterval(()=>{if(!running)runCrawler();},Math.max(1,Number(process.env.AUTO_CRAWL_LOOP_HOURS||6))*3600000).unref();
